### PR TITLE
Another attempt to fix #1135

### PR DESCRIPTION
**Pull request by DeltaQuad-DQ**

### CODE REVIEW

**Comment by DeltaQuad-DQ** [comment]
So can someone please merge this? @labster @Reception123

**Comment by DeltaQuad-DQ** [comment]
Hello? This has been sitting here for over 12 hours and is not requesting anything brand-new. Please merge this, someone. @JohnFLewis @Reception123

**Comment by Reception123** [comment]
I don't currently have access and I am not sure if this would fix the problem anyway.

**Comment by DeltaQuad-DQ** [comment]
@Reception123 Well, you won't know if it fixes the problem without trying. This was @The-Voidwalker's suggestion. And what do you mean you "don't have access"? You've merged a whole plethora of requests recently.

**Comment by Reception123** [comment]
I mean that I am not on my PC right now meaning that if something were to go wrong the site would have to be down for more than 10 minutes as I can't run puppet.

**Comment by DeltaQuad-DQ** [comment]
Success!

**Pull request merged**
