### PR TITLE
Add $wgAbuseFilterRestrictions

### PR DESCRIPTION
**Pull request by Amanda1234567**

### CODE REVIEW

**Comment by Arcane21** [comment]
I looked over this commit, and I'd advise Miraheze Staff against it.

It effectively leaves the Abuse Filter toothless except to block IP ranges on the wikicanada wiki, and I see no good reason to defang that extension on any individual wiki.

**Comment by The-Voidwalker** [comment]
~~Actually, all it does is makes rangeblock the only abusefilter function that requires the right `abusefilter-modify-restricted` on wikicanadawiki.~~

~~It has no effect on the current global abusefilter setup.~~

The above would apply if the proper syntax had been used.

`'default' => array( 'block', 'degroup', 'blockautopromote', 'rangeblock' ),`
`'wikicanadawiki' => array( 'rangeblock' ),`

**Comment by Amanda1234567** [comment]
Happened to wake up for a minute and saw this comment. 

I will not be active for the rest of the evening as I am resting from a cold

**Comment by The-Voidwalker** [comment]
Hold on, it might be that the documentation is not up to date. Something is not adding up

**Comment by The-Voidwalker** [comment]
Ok, turns out you had it right the first time, except the variable name is `wgAbuseFilterRestrictions`. My apologies. I'm going to go edit the documentation on mediawiki.org.

**Comment by Arcane21** [comment]
Glad to hear I was in error. 

I'm just glad to see the ability of staff to globally police all wikis regardless of individual preferences per wiki is not compromised in any way.

**Pull request merged**
