### PR TITLE
Create public/private wiki list

### PR DESCRIPTION
**Pull request by AgentIsai**
Useful for wiki backups

### CODE REVIEW

**Comment by Universal-Omega** [comment]
What is the reason here? More DB lists = worse performance so if there isn't an absolute necessity they shouldn't be done.

**Comment by AgentIsai** [comment]
> What is the reason here? More DB lists = worse performance so if there isn't an absolute necessity they shouldn't be done.

Really? Little things like this should be documented. Otherwise, I thought it was because no one had thought about it.

**Comment by Universal-Omega** [comment]
Hmm maybe I fixed the worse performance with more lists now lol

**Comment by Universal-Omega** [comment]
They just don't update unless databases.php until is updated.

**Comment by AgentIsai** [comment]
Should we see if any performance issues occur?

**Comment by Universal-Omega** [comment]
Yeah we can try this. I actually do believe I fixed it with my recent changes.

**Comment by AgentIsai** [comment]
Very well.

**Pull request merged**
