### PR TITLE
SCSVG: setup

### PR DESCRIPTION
**Pull request by RhinosF1**
- [x] memcache
- [x] wfHostname
- [x] DB Servers
- [x] Linter allowlist
- [x] populate IPs

### CODE REVIEW

**Comment by RhinosF1** [comment]
smoke test on test3 looked fine. I logged in to beta & made an edit then reverted. No errors seen.

**Comment by Universal-Omega** [comment]
This kinda makes a mess of things. This should be temporary if we do it like this. Therefore I don't think $wmgCacheSettings should really be completely removed.

**Comment by RhinosF1** [comment]
> This kinda makes a mess of things. This should be temporary if we do it like this. Therefore I don't think $wmgCacheSettings should really be completely removed.

Is it not easier to find the information if it's it one file?

But the actual arrays will be temporary and anything old DC related once we're on SCSVG fully

**Comment by RhinosF1** [comment]
Explained on IRC better

**Review by Universal-Omega — APPROVED** [review]

**Pull request merged**
