### PR TITLE
Add db172

### PR DESCRIPTION
**Pull request by redbluegreenhat**

### CODE REVIEW

**Comment by Universal-Omega** [comment]
This should be c1 — on beta with two seperate setups entirely.

**Comment by redbluegreenhat** [comment]
> This should be c1 — on beta with two seperate setups entirely. It reduces the chance of accidentally using it in production if something goes wrong.

Like define two separate `$wgLBFactoryConf` depending on the hostname?

**Comment by Universal-Omega** [comment]
> > This should be c1 — on beta with two seperate setups entirely. It reduces the chance of accidentally using it in production if something goes wrong.
> 
> Like define two separate `$wgLBFactoryConf` depending on the hostname?

This is what I was thinking, as that way the clusters only exist in the correct realm and not exist at all otherwise. Maybe even a seperate Databases-beta.php or something.

**Comment by Universal-Omega** [comment]
I can't review this in depth right now but looks okay on a glance. Feel free to do it if you feel like it is correct now.

**Pull request merged**
