### PR TITLE
Reenable MediaWikiChat on extloadwiki

### PR DESCRIPTION
**Pull request by LegoFan4000**

### CODE REVIEW

**Comment by Reception123** [comment]
Please remove my message next to it in that case and also I will wait for @NDKilla as I'm not sure if the directories were successfully copied.

**Comment by JohnFLewis** [comment]
@Reception123 I don't get what we're waiting for here. There are no directories for this extension.

**Comment by Reception123** [comment]
There were the SQL files, but I guess @NDKilla did merge them so I'll go ahead and merge this as it's only extloadwiki in any case.

**Comment by Reception123** [comment]
@JohnFLewis Apparently, the database changes weren't made per #809

**Comment by LegoFan4000** [comment]
Maybe run Update.php

**Comment by Reception123** [comment]
@LegoFan4000 We do not run update.php except while doing a MediaWiki update or in extreme cases.

**Comment by JohnFLewis** [comment]
The daabase tables definitely exist. The issue is the LC cache wasn't rebuilt.

**Comment by LegoFan4000** [comment]
How can we fix that.

**Comment by Reception123** [comment]
I have already fixed it by changing the extension configuration back to require_once. It has been now been enabled.

**Pull request merged**
