### PR TITLE
set wgLexemeLanguageCodePropertyId and wgLexemeEnableDataTransclusion for gratisdatawiki

### PR DESCRIPTION
**Pull request by ugochimobi**

### CODE REVIEW

**Review by Universal-Omega — CHANGES_REQUESTED** [review]
Could be added to ManageWiki instead.

**Comment by ugochimobi** [comment]
> Could be added to ManageWiki instead.

But they're not in ManageWiki yet? No?

**Comment by Universal-Omega** [comment]
> > Could be added to ManageWiki instead.
> 
> But they're not in ManageWiki yet? No?

No. I'm saying we could add it.

**Comment by ugochimobi** [comment]
> > > Could be added to ManageWiki instead.
> > 
> > 
> > But they're not in ManageWiki yet? No?
> 
> No. I'm saying we could add it.

Okay okay, let's do it! 😊

**Comment by Universal-Omega** [comment]
> > > > Could be added to ManageWiki instead.
> > > 
> > > 
> > > But they're not in ManageWiki yet? No?
> > 
> > 
> > No. I'm saying we could add it.
> 
> Okay okay, let's do it! 😊

I can maybe tomorrow if you'd like?

**Comment by ugochimobi** [comment]
> > > > > Could be added to ManageWiki instead.
> > > > 
> > > > 
> > > > But they're not in ManageWiki yet? No?
> > > 
> > > 
> > > No. I'm saying we could add it.
> > 
> > 
> > Okay okay, let's do it! 😊
> 
> I can maybe tomorrow if you'd like?

I might not be able to, it seems a little conplex for me since I haven't committed to ManageWiki before... I would have submitted a PR .... Let's wait till you do it :)

**Comment by Universal-Omega** [comment]
> > > > > > Could be added to ManageWiki instead.
> > > > > 
> > > > > 
> > > > > But they're not in ManageWiki yet? No?
> > > > 
> > > > 
> > > > No. I'm saying we could add it.
> > > 
> > > 
> > > Okay okay, let's do it! 😊
> > 
> > 
> > I can maybe tomorrow if you'd like?
> 
> I might not be able to, it seems a little conplex for me since I haven't committed to ManageWiki before... I would have submitted a PR .... Let's wait till you do it :)

I will tomorrow. Leaving this open to remind me until then.

**Comment by ugochimobi** [comment]
> 

Nice nice!

**Comment by Universal-Omega** [comment]
* #4666

**Pull request closed without merging**
