### PR TITLE
Does this work?

### PR DESCRIPTION
**Pull request by DeltaQuad-DQ**
Just for my knowledge, does this code work to have a local wiki opt-out of global extensions?

### CODE REVIEW

**Comment by DeltaQuad-DQ** [comment]
I'm going to assume that the answer is no, since the default check has failed

**Comment by JohnFLewis** [comment]
Indeed, nope.

**Comment by DeltaQuad-DQ** [comment]
Is there a possible way to do this @JohnFLewis

**Comment by JohnFLewis** [comment]
Nope.

**Comment by DeltaQuad-DQ** [comment]
So local wikis can opt out of global sitenotices and global defaults of permissions, but they can't opt out of global extensions?

**Comment by JohnFLewis** [comment]
Yes because those are handled in different ways. Inclusion of global extensions is loading everything in a file and then including it.

**Comment by DeltaQuad-DQ** [comment]
And I gather it's not technically possible to unload everything out of a local file and then exclude it from specified wikis

**Comment by JohnFLewis** [comment]
Nope

**Pull request closed without merging**
