### PR TITLE
Update wgHAWelcomeWelcomeUsername default

### PR DESCRIPTION
**Pull request by Universal-Omega**

### CODE REVIEW

**Review by dmehus — APPROVED** [review]
:+1: LGTM.

Was `$wi->sitename` even a recommended default value by the extension?

**Review by dmehus — APPROVED** [review]
:+1:

**Comment by Universal-Omega** [comment]
> 👍 LGTM.
> 
> Was `$wi->sitename` even a recommended default value by the extension?

No, the default was ShoutWiki.

**Comment by dmehus** [comment]
> > 👍 LGTM.
> > Was `$wi->sitename` even a recommended default value by the extension?
> 
> No, the default was ShoutWiki.

Ah, okay, yeah. This is much better.

**Pull request merged**
