### PR TITLE
Update LocalSettings.php

### PR DESCRIPTION
**Pull request by Naleksuh**

### CODE REVIEW

**Comment by Universal-Omega** [comment]
This should not be done. This will enable Global site CSS/JS, meaning it will make metawiki MediaWiki:Global.css/MediaWiki:Global.js, effect all wikis, from my understanding.

**Comment by Naleksuh** [comment]
> This should not be done. This will enable Global site CSS/JS, meaning it will make metawiki MediaWiki:Global.css/MediaWiki:Global.js, effect all wikis, from my understanding.

Yes, that's the purpose of the page. Doesn't explain why it "should not be done", that explains why it _should_

**Comment by Universal-Omega** [comment]
> > This should not be done. This will enable Global site CSS/JS, meaning it will make metawiki MediaWiki:Global.css/MediaWiki:Global.js, effect all wikis, from my understanding.
> 
> Yes, that's the purpose of the page. Doesn't explain why it "should not be done", that explains why it _should_

We won't interfere with global community wiki site-wide CSS/JS. Doing this will likely need to go through the community.

**Comment by Naleksuh** [comment]
Right now, Global.js is empty but Global.css has some CSS on it. Not sure what it does but it probably belongs there. This needs to be future proofed instead of requiring multiple steps to edit a page.

**Comment by Universal-Omega** [comment]
> Right now, Global.js is empty but Global.css has some CSS on it. Not sure what it does but it probably belongs there. This needs to be future proofed instead of requiring multiple steps to edit a page.

Doing this would allow interface-admins to make global changes also. As for why it has CSS in it, it was added by Dmehus after a request a SN, likely not realizing that we don't use it as we should not make Global style changes. We shouldn't enable this without it at least going through an RfC first. It effects the global community and the level of interference with local communities that can be done from metawiki.

**Pull request closed without merging**
