### PR TITLE
Adds $wgLogos support in ManageWiki (T6164 | T6361 | T6364)

### PR DESCRIPTION
**Pull request by Universal-Omega**
This sets the value of `$wgLogos['1x']` equal to the value of `$wgLogo` (T6361) and changes the type in ManageWiki for `$wgLogo` from text to url. This also adds the configuration option for `$wgLogos['wordmark']['src']` to ManageWiki to allow changing the Minerva copyright wordmark from ManageWiki. (T6164 | T6364)

### CODE REVIEW

**Review by RhinosF1 — CHANGES_REQUESTED** [review]
See travis

**Comment by Universal-Omega** [comment]
> See travis

Fixed those syntax errors I think.

**Review by RhinosF1 — CHANGES_REQUESTED** [review]
See comment

**Review by RhinosF1 — APPROVED** [review]

**Comment by RhinosF1** [comment]
Nothing obvious.

**Comment by Universal-Omega** [comment]
> Nothing obvious.

Yeah thanks! I completely missed the apostrophe last time. My bad.

**Pull request merged**
