### PR TITLE
Redo #2557

### PR DESCRIPTION
**Pull request by revi**
It still sucks. Why was it undid after all?

Ref: #2557

### CODE REVIEW

**Comment by paladox** [comment]
See https://github.com/miraheze/mw-config/blob/6d774a8ce7ff74e9195cdae44d31a1d0035c4b1d/LocalSettings.php#L3011

**Comment by Pix1234** [comment]
Merging as i dont see where or why it was ever removed

**Comment by JohnFLewis** [comment]
Per Paladox this is in LS.

**Comment by Pix1234** [comment]
> Per Paladox this is in LS.

Yeah, only saw after i pressed merged as thats when the comment was loaded on the page for me, reverted

**Pull request merged**
