### PR TITLE
Un-restrict $wgFileExtensions; add $wgFileBlacklist to still restrict dangerous ones.

### PR DESCRIPTION
**Pull request by Universal-Omega**

### CODE REVIEW

**Comment by JohnFLewis** [comment]
Splitting to two settings seems unnecessary when HTMLForm has support for disabled elements in a list. Support should be added to ManageWiki for such a case, rather than leaving it down to a configuration problem

**Comment by Universal-Omega** [comment]
> Splitting to two settings seems unnecessary when HTMLForm has support for disabled elements in a list. Support should be added to ManageWiki for such a case, rather than leaving it down to a configuration problem

Fair enough. Although we probably don't need wgFileBlacklist, just removing the $wgFileBlacklist extensions from $wgFileExtensions should be the same, if that'd be easier for you, since those extensions never worked anyways per https://www.mediawiki.org/wiki/Manual:$wgFileBlacklist

**Review by Pix1234 — APPROVED** [review]
Don't really need to be able to upload .crt but LGTM

**Comment by Universal-Omega** [comment]
> Don't really need to be able to upload .crt but LGTM

5 wikis have that extension enabled for upload.

**Comment by dmehus** [comment]
For what it's worth, I'm not sure about unrestricting this many extensions. I wouldn't mind seeing certain extensions like, `*.zip` and `*.7z` and a few others, remaining as `managewiki-restricted`. I think we can still be liberal with granting wikis the ability to use these extensions, but having a Steward review the request provides an appropriate check / second pair of eyes

**Comment by Universal-Omega** [comment]
> For what it's worth, I'm not sure about unrestricting this many extensions. I wouldn't mind seeing certain extensions like, `*.zip` and `*.7z` and a few others, remaining as `managewiki-restricted`. I think we can still be liberal with granting wikis the ability to use these extensions, but having a Steward review the request provides an appropriate check / second pair of eyes

I can't say I completely disagree with you but I also think that we really don't need to keep zip and 7z restricted if they're almost always approved anyways, and archives such as these typically aren't to dangerous also but I suppose this could be investigated/looked into further first.

**Pull request merged**
