### PR TITLE
Add Citoid sitenotice

### PR DESCRIPTION
**Pull request by Universal-Omega**

### CODE REVIEW

**Comment by dmehus** [comment]
> > Why use a sysadmin sitenotice and not a central notice, drafted in collaboration with Stewards? I also take issue with the proposed _wording_ of this sitenotice. SRE should be consulting with the community's elected functionaries on this. Ideally, this should be a central notice that links to an explanatory page outlining the purpose of the Citoid extension, any extension or other dependencies, the RESTbase server, what SRE aims to achieve by decommissioning the RESTbase server (including where it proposes to reallocate resources), examines a more fulsome dataset, what team within SRE has proposed its removal, and then links to the community discussion from there. A one- or two-line SRE-drafted sysadmin sitenotice stating simply that it proposes to remove the extension doesn't satisfy me in terms of SRE fulfilling its community consultation obligations and commitments
> 
> Sure. Wording can be changed. As for doing it with the sysadmin site notice is so that it is only shown on wikis with the Citoid extension enabled.

Okay, but I just saw that the Citoid extension requires `managewiki-restricted` user rights, which only SRE, Stewards, and Trust & Safety team members have. It holds that it's not enabled on many wikis, so perhaps the reason it's under-utilized is because it's a restricted extension. This is the extension that powers the citation templates on English Wikipedia and elsewhere, though yes it can be complicated to have all of that set up

**Comment by dmehus** [comment]
> > > > Why use a sysadmin sitenotice and not a central notice, drafted in collaboration with Stewards? I also take issue with the proposed _wording_ of this sitenotice. SRE should be consulting with the community's elected functionaries on this. Ideally, this should be a central notice that links to an explanatory page outlining the purpose of the Citoid extension, any extension or other dependencies, the RESTbase server, what SRE aims to achieve by decommissioning the RESTbase server (including where it proposes to reallocate resources), examines a more fulsome dataset, what team within SRE has proposed its removal, and then links to the community discussion from there. A one- or two-line SRE-drafted sysadmin sitenotice stating simply that it proposes to remove the extension doesn't satisfy me in terms of SRE fulfilling its community consultation obligations and commitments
> > > 
> > > 
> > > Sure. Wording can be changed. As for doing it with the sysadmin site notice is so that it is only shown on wikis with the Citoid extension enabled.
> > 
> > 
> > Okay, but I just saw that the Citoid extension requires `managewiki-restricted` user rights, which only SRE, Stewards, and Trust & Safety team members have. It holds that it's not enabled on many wikis, so perhaps the reason it's under-utilized is because it's a restricted extension. This is the extension that powers the citation templates on English Wikipedia and elsewhere, though yes it can be complicated to have all of that set up
> 
> It was only just restricted after the discussion was ongoing.

Hrm? Why make it restricted before the discussion had closed? I don't get the rationale there. Shouldn't that wait until it concludes?

**Comment by Universal-Omega** [comment]
> > > > > Why use a sysadmin sitenotice and not a central notice, drafted in collaboration with Stewards? I also take issue with the proposed _wording_ of this sitenotice. SRE should be consulting with the community's elected functionaries on this. Ideally, this should be a central notice that links to an explanatory page outlining the purpose of the Citoid extension, any extension or other dependencies, the RESTbase server, what SRE aims to achieve by decommissioning the RESTbase server (including where it proposes to reallocate resources), examines a more fulsome dataset, what team within SRE has proposed its removal, and then links to the community discussion from there. A one- or two-line SRE-drafted sysadmin sitenotice stating simply that it proposes to remove the extension doesn't satisfy me in terms of SRE fulfilling its community consultation obligations and commitments
> > > > 
> > > > 
> > > > Sure. Wording can be changed. As for doing it with the sysadmin site notice is so that it is only shown on wikis with the Citoid extension enabled.
> > > 
> > > 
> > > Okay, but I just saw that the Citoid extension requires `managewiki-restricted` user rights, which only SRE, Stewards, and Trust & Safety team members have. It holds that it's not enabled on many wikis, so perhaps the reason it's under-utilized is because it's a restricted extension. This is the extension that powers the citation templates on English Wikipedia and elsewhere, though yes it can be complicated to have all of that set up
> > 
> > 
> > It was only just restricted after the discussion was ongoing.
> 
> Hrm? Why make it restricted before the discussion had closed? I don't get the rationale there. Shouldn't that wait until it concludes?

Honestly I don't know exactly why. But I do think restricting it while discussion is ongoing was fine also.

**Comment by dmehus** [comment]
To be clear, I'm not necessarily completely opposed to removing this extension, but I //do// feel that given the potential impacts this would have on potential future informational or bibliographic repository-type wikis, as it reenabling it would require setting up a new RESTbase server, this needs a full informational case page that outlines SRE's case for all of the above. Once everyone fully understands both the extension and where SRE intends to reallocate those saved resources, as well potential lost use cases, and a somewhat elongated community consultation period, I'd be fine with removing it if there's no significant opposition to its removal. I just don't feel there's a strong case for both an accelerated decommissioning and deinstallation process and for not drafting an informational case page.

**Pull request closed without merging**
