### PR TITLE
Change copyright license on wikilexicon.miraheze.org per T5318

### PR DESCRIPTION
**Pull request by Hispano76**

### CODE REVIEW

**Comment by RhinosF1** [comment]
Spoke to Owen, SRE can the the response on Discord or ping me and I’ll send it.

People involved in the v3-v4 switch should probably comment.

Again, ManageWiki if acceptable?

**Comment by soratako** [comment]
Hi, RhinosF1.  Thanks for your comments. But I have to apologize. I couldn't fully understand your comments because of my poor English skill. Could you explain without using abbreviations? What does SRE stand for? What does v3, v4 stand for? What does MW stand for?

**Comment by RhinosF1** [comment]
> Hi, RhinosF1. Thanks for your comments. But I have to apologize. I couldn't fully understand your comments because of my poor English skill. Could you explain without using abbreviations? 

Don’t worry!

> What does SRE stand for? 

Site Reliability Engineering

> What does v3, v4 stand for? 

Versions of the license

> What does MW stand for?

Manage Wiki

**Comment by soratako** [comment]
Thank you very much!  It seems no problem to me. V4-v3 is a community decision and posts prior to the change have been licensed v3.

**Comment by paladox** [comment]
Where is this discussion? And did everyone who edited on the wiki, respond with a "i approve the downgrade"?

**Comment by paladox** [comment]
Sorry a co-worker gave me the link to the task. そらたこテスト, そらたこ, Houyagokusai, キノ, シュヴァルツ , セロン and 令和少年  have not put there names against "Attribution-ShareAlike 3.0 Unported (ウィキペディアと同じ)". Until that is done, this cannot be merged (legally).

You can use https://wikilexicon.miraheze.org/wiki/特別:登録利用者一覧 to help match users who have commented on https://wikilexicon.miraheze.org/wiki/議論の場:ウィキのライセンスについて

**Comment by soratako** [comment]
Hi, paladox! Thanks for ur comments. But that is a mistake. The section you are looking at is a vote on the new license. Permissions for new licensing is obtained in the section "許諾". Approved by 7 accounts of the 10 contributors. And, "そらたこテスト" is my subaccount, "キノ" is "セロン"'s subaccount. "MediaWiki default" is a bot, no need to consider.

**Comment by soratako** [comment]
Also, I forgot, "Houyagokusai" made its first contribution after Phab's request and the new license is confirmed. I have announced using Sitenotice, Mediawiki:Copyrightwarning, MediaWiki:Copyright, MediaWiki:Mobile-frontend-copyright until request to Phab. So, submissions after confirmation (request to Phab) are v-3 at the time of submission.

**Comment by soratako** [comment]
was

**Comment by paladox** [comment]
Houyagokusai needs to comment there too.

**Comment by soratako** [comment]
Why? Are those announcements not enough?

**Comment by paladox** [comment]
No, everyone who has ever written on your wiki must confirm that they approve the licensing change. And also unless your sub accounts say its an alt of your main, they must comment on the page too. I'm sorry that we are asking this, but we don't have any choice (these are not our rules).

**Comment by soratako** [comment]
It has been decided locally that the license change will be confirmed at the time of the phab request.  This was announced by Sitenotice before the phab request. 

Houyagokusai created an account after the newlicense notice and all posts are licensed new license.

Subaccounts are announced on the userpage of each main account. そらたこテスト was created by me(そらたこ) on soratako.miraheze.org.

**Comment by soratako** [comment]
Houyagokusai's permission has been obtained.

Diff: https://wikilexicon.miraheze.org/wiki/Special:Diff/1384

**Comment by soratako** [comment]
Contributions by the "そらたこテスト" have been deleted.

We are now ready to make licensechange.

**Comment by soratako** [comment]
……

**Pull request merged**
