### PR TITLE
Update poweredby

### PR DESCRIPTION
**Pull request by Universal-Omega**

### CODE REVIEW

**Comment by dmehus** [comment]
LGTM. 👍

**Comment by MacFan4000** [comment]
While the new footer button looks ok, the community should have been consulted about this beforehand. This is a visual change affecting all wikis. Changes like this should not be done without first having an RFC.

**Comment by RhinosF1** [comment]
This definately should have been consulted on.

**Comment by MacFan4000** [comment]
I opened an RFC to ratify this change. https://meta.miraheze.org/wiki/Requests_for_Comment/Changing_the_Powered_by_Miraheze_footer_button

**Comment by Universal-Omega** [comment]
Apologies. I was told by Agent and Doug the community likely didn't. As it was uncontroversial. Which is why I just deployed this.

**Pull request merged**
