### PR TITLE
WBQuality constraint configs for gratisdatawiki

### PR DESCRIPTION
**Pull request by ugochimobi**
These variables aren't available from ManageWiki, and If it should be added to managewiki, it is going to be possible to add more than one value?
So, please review and merge appropriately.

### CODE REVIEW

**Review by Universal-Omega — APPROVED** [review]
Defaults confirmed, seems OK.

**Comment by ugochimobi** [comment]
Of course, let's wait for it (ManageWiki) to be updated then.

**Comment by Universal-Omega** [comment]
I've just added the new 'texts' to the comment at the top of ManageWikiSettings.

**Comment by Universal-Omega** [comment]
I've just added the new 'texts' to the comment at the top of ManageWikiSettings, this should work for these configs.

**Comment by ugochimobi** [comment]
Oh, let me see if it works.

**Comment by Universal-Omega** [comment]
Please do another PR if you wish to add these to ManageWiki.

**Comment by ugochimobi** [comment]
> Please do another PR if you wish to add these to ManageWiki.

Alright 👍

**Pull request merged**
