### PR TITLE
Add '.*scratch' to rw blacklist

### PR DESCRIPTION
**Pull request by examknow**
Adding rule per the request of @RhinosF1 who I assume will comment with more regarding the reason for this request.

### CODE REVIEW

**Comment by examknow** [comment]
Tbh banning a wiki topic should be a community or at the very least a steward issue.

**Comment by RhinosF1** [comment]
My suggestion is this is put in place for 28 days to allow time for community discussion

**Comment by sario528** [comment]
I agree that we should give the community a chance to comment on this.

**Comment by examknow** [comment]
@RhinosF1 I would suggest you open up an RfC. We can keep this PR open until we have some community opinion.

**Comment by RhinosF1** [comment]
A post will be made within the next day to allow discussion.

I only intend for this to be a temp solution until we can harden the content policy to prevent it.

**Comment by Reception123** [comment]
@RhinosF1 status?

**Comment by RhinosF1** [comment]
Waiting on RfC result

**Comment by Pix1234** [comment]
Merging per [successful 45 day ban proposal ](https://meta.miraheze.org/wiki/Requests_for_Comment/Prohibit_hate-based_wikis)

**Pull request merged**
