### PR TITLE
cineama wiki changes

### PR DESCRIPTION
**Pull request by NDKilla**
requested on irc 

(might have to revoke some permissions from user, question wasn't answered)

### CODE REVIEW

**Comment by Reception123** [comment]
Don't forget to add MU and VE

**Comment by revi** [comment]
>This branch has conflicts that must be resolved

You want to resolve conflicts by me or you will resolve them?

**Comment by TheTVFan** [comment]
I would like someone to resolve the conflicts...

**Comment by NDKilla** [comment]
@revi would love it if you could fix :)
btw added you to https://github.com/NDKilla/mw-config/ collab

**Comment by TheTVFan** [comment]
$wgGroupPermissions['sysop']['bigdelete'] = false  - it should be true ;) can you fix?

**Comment by NDKilla** [comment]
@thetvfan that should definitely not be true. (In this PR). That is an already in effect global setting not specific to your wiki. Sysops may delete pages but big delete is for deleting pages with over 250 revisions. Big delete limits vary wiki-farm to farm but most places leave bigdelete for sysadmins because of limitations of resources. The db servers don't have much ram which is why this limit is set

**Comment by NDKilla** [comment]
@thetvfan https://www.mediawiki.org/wiki/Manual:$wgDeleteRevisionsLimit

**Comment by TheTVFan** [comment]
Ok @NDKilla, I thought it was an option to mass delete pages on the wiki. :)

**Comment by JohnFLewis** [comment]
The limit is honestly a plucked number out of no where. it'll get adjusted as we see how loads cope with large deletions. 250 is probably way below the limit of the database server. It's just the case that allowing everyone to delete pages with large revisions can lag databases and worst case crash them.

**Comment by revi** [comment]
Will do, when I have time.

**Comment by NDKilla** [comment]
@revi group permissions false doesn't work inside of wg conf (something special was done on Orain and not sure how that even works). 

This can be tested by ctrl+f'ing the file to see the one wiki with a group permission set to false, then going to "Special:ListGroupRights" on that wiki.

**Pull request merged**
