### PR TITLE
config changes for bonobowiki

### PR DESCRIPTION
**Pull request by robkam**

### CODE REVIEW

**Comment by Reception123** [comment]
@robkam the file revi is referring to is https://github.com/miraheze/parsoid/blob/master/parsoid.yaml

**Comment by robkam** [comment]
thanks, now added bonobowiki to parsoid.yaml

**Comment by revi** [comment]
Sorry, I was unclear what I meant. Merging now!

**Comment by robkam** [comment]
NP. I’m still trying to figure out how to do things. Thanks.

**Pull request merged**
