### PR TITLE
Update LocalSettings.php

### PR DESCRIPTION
**Pull request by aliftah**
disable users from editing

### CODE REVIEW

**Comment by Reception123** [comment]
You need to include your wiki name. This is done in LocalWiki.php

**Comment by aliftah** [comment]
my wiki name is 
nvu.miraheze.org

**Comment by aliftah** [comment]
i can edit it in my local host 
but i cant edit it in the github

**Comment by Reception123** [comment]
@aliftah Sorry, I did not look properly. This is done by wmgEditingMatrix, I will do it for you. Also, accounts are shared on Miraheze so disabling "createaccount" wouldn't do anything.

**Pull request closed without merging**
