### PR TITLE
rem editor group from cinemawiki+disable anon edit per IRC req

### PR DESCRIPTION
**Pull request by Reception123**

### CODE REVIEW

**Comment by revi** [comment]
Blocked by ```editors``` assigned to users:
```
AdvancedAzrielAngel (토론 | 기여 | 차단)‏‎ (editor) (2015년 9월 24일 (목) 06:00에 계정이 만들어짐)
Grisby49 (토론 | 기여 | 차단)‏‎ (editor) (2015년 9월 21일 (월) 20:58에 계정이 만들어짐)
Reception123 (토론 | 기여 | 차단)‏‎ (autopatrolled, editor) (2015년 9월 22일 (화) 16:35에 계정이 만들어짐)
Southparkfan (토론 | 기여 | 차단)‏‎ (autopatrolled, editor) (2015년 9월 20일 (일) 16:44에 계정이 만들어짐)
```

**Comment by Reception123** [comment]
@revi Will tell user to remove them

**Comment by TheTVFan** [comment]
Removed

**Comment by Reception123** [comment]
@revi ^

**Pull request merged**
