### PR TITLE
Change refreshed to wfload

### PR DESCRIPTION
**Pull request by LegoFan4000**

### CODE REVIEW

**Comment by Reception123** [comment]
Will check this out later.

**Comment by Reception123** [comment]
Will merge but if anything goes wrong I will have to revert.

**Comment by Reception123** [comment]
@LegoFan4000 As you can see above, it didn't work.

**Comment by labster** [comment]
Of course it's not going to work if you don't put quote marks around the name of the skin.

**Comment by labster** [comment]
Actually never mind that last comment, I forget how terrible a language PHP is.

**Pull request merged**
