### PR TITLE
add skipcaptcha to autopatrolled and confirmed

### PR DESCRIPTION
**Pull request by Wynter**

### CODE REVIEW

**Comment by Reception123** [comment]
I am not sure this is need as we do have the "skicaptcha" right

**Comment by Reception123** [comment]
I am not sure this is needed as we do have the "skicaptcha" right
@Southparkfan What do you think?

**Comment by NDKilla** [comment]
I don't see a reason not to give it to confirmed (at the least) and just remove the skipcaptcha right.

**Comment by Reception123** [comment]
I perfectly agree with what @NDKilla said. But we can't have both. Either add the skipcaptcha right to confirmed and delete it, or not add it at all.

**Pull request merged**
