### PR TITLE
add SocialProfile to microsoftwiki per req

### PR DESCRIPTION
**Pull request by Reception123**
// Requires copying of two directories: https://www.mediawiki.org/wiki/Extension:SocialProfile#Directories
	// Requires run of update.php!!

### CODE REVIEW

**Comment by Reception123** [comment]
@Southparkfan @revi @JohnFLewis

**Comment by JohnFLewis** [comment]
Needs copying of directory but not uodate.php.

**Comment by JohnFLewis** [comment]
Still not handled? bah.

**Comment by JohnFLewis** [comment]
Handled by @labster already it seems.

**Pull request closed without merging**
