### PR TITLE
T10446: Set wgAllowImageTag for dgck81lnnwiki

### PR DESCRIPTION
**Pull request by redbluegreenhat**
Requested on Phabricator: https://phabricator.miraheze.org/T10446.

### CODE REVIEW

**Comment by Universal-Omega** [comment]
It was deprecated and causes warnings in our logs IIRC. In my opinion this shouldn't be set for any wiki.

**Comment by redbluegreenhat** [comment]
I kinda think the same thing, tbh. Your call.

**Comment by DGCK81LNN** [comment]
If enabling this will lead to warnings then I shall not insist. It seems not all external images are allowed on Miraheze anyway, due to some HTTP headers. Please close this issue.

**Comment by Universal-Omega** [comment]
Closing per above.

**Pull request closed without merging**
