### PR TITLE
Cleanups

### PR DESCRIPTION
**Pull request by Universal-Omega**

### CODE REVIEW

**Comment by dmehus** [comment]
These all LGTM. My only concern is this commit **[eaa0ade](https://github.com/miraheze/mw-config/pull/3356/commits/eaa0ade17459dd391d15dc043727c4bd4bf26414)**. This will _not_ delete those special pages, will it? Can you explain what this to-be-deleted file actually did?

**Comment by Universal-Omega** [comment]
> These all LGTM. My only concern is this commit **[eaa0ade](https://github.com/miraheze/mw-config/pull/3356/commits/eaa0ade17459dd391d15dc043727c4bd4bf26414)**. This will _not_ delete those special pages, will it? Can you explain what this to-be-deleted file actually did?

As far as I could tell it did nothing

**Comment by Pix1234** [comment]
Im not sure about this tbh, im going to wait for @paladox to sign off

**Comment by Universal-Omega** [comment]
> Im not sure about this tbh, im going to wait for @paladox to sign off

Yeah, I planned on verifing with Paladox or Southparkfan also.

**Comment by Universal-Omega** [comment]
Done in #3373, #3374, #3375, #3376, #3377, #3378, #3379, and #3380

**Pull request closed without merging**
