### PR TITLE
TE and XCON protection levels on GP

### PR DESCRIPTION
**Pull request by ugochimobi**
Please review codes and merge appropriately, ;)

### CODE REVIEW

**Review by dmehus — COMMENTED** [review]
This looks fine to me, but I believe will also need to these user rights to the additional ManageWiki rights, so they can be assigned in ManageWiki/permissions.

**Comment by ugochimobi** [comment]
> This looks fine to me, but I believe will also need to these user rights to the additional ManageWiki rights, so they can be assigned in ManageWiki/permissions.

TBH, that wouldn't be a bad idea

**Comment by Universal-Omega** [comment]
> > This looks fine to me, but I believe will also need to these user rights to the additional ManageWiki rights, so they can be assigned in ManageWiki/permissions.
> 
> TBH, that wouldn't be a bad idea

Rights need added to $wgAvailableRights for this.

**Comment by dmehus** [comment]
> > > This looks fine to me, but I believe will also need to these user rights to the additional ManageWiki rights, so they can be assigned in ManageWiki/permissions.
> > 
> > 
> > TBH, that wouldn't be a bad idea
> 
> Rights need added to $wgAvailableRights for this.

Thanks, I couldn't think of the exact variable for that. :)

**Comment by ugochimobi** [comment]
Okay, I just did it.

**Comment by ugochimobi** [comment]
Okay @Universal-Omega I just did it here.

**Pull request merged**
