### PR TITLE
Not exactly sure what this right is for

### PR DESCRIPTION
**Pull request by DeltaQuad-DQ**
But it doesn't have access to any restricted interfaces, so....

### CODE REVIEW

**Comment by Reception123** [comment]
I would merge but I'm not 100% sure if spaces are allowed for permissions. Please wait for someone else to double check.

**Comment by DeltaQuad-DQ** [comment]
The user group as defined by the extension, as defined in Special:UserRights and as defined in Special:ListGroupRights has a space. Also note that the "check user" group has a space without issues.

**Comment by Reception123** [comment]
@DeltaQuad-DQ I checked the file and there it seems to be possible so I will merge.

**Comment by JohnFLewis** [comment]
Though in future, please use lowercase.

**Comment by DeltaQuad-DQ** [comment]
@JohnFLewis The group is defined as uppercase in the extension

**Comment by JohnFLewis** [comment]
But we prefer lowercase. It's consistency among us.

**Comment by DeltaQuad-DQ** [comment]
Err... that didn't work. That created a brand-new "Flow bot" user group and didn't add the permissions to the existing predefined one like I wanted. If you go to Special:ListGroupRights on elements.miraheze.org you will see what I am talking about.

**Comment by JohnFLewis** [comment]
https://github.com/wikimedia/mediawiki-extensions-Flow/blob/bc94b5d247990d4214d08e7daf54333b5894df55/Flow.php#L201

The group is called "flow-bot" which matches our standards of lowercase and no spaces.

**Comment by DeltaQuad-DQ** [comment]
Oops. Will fix now.

**Pull request merged**
