### PR TITLE
Blacklist sensitive user rights from being `*`

### PR DESCRIPTION
**Pull request by dmehus**
Per internal discussion with @The-Voidwalker and @JohnFLewis

### CODE REVIEW

**Comment by dmehus** [comment]
We'll need to also run a query to determine which wikis have assigned any of these user rights to `*`, and then run a separate query to remove them from same.

**Comment by dmehus** [comment]
@Universal-Omega Can you figure out the query we can run to see (a) which wikis had set any of these user rights to `*` and of those that did (b) a second query that removes the listed rights from `*`?

**Comment by Universal-Omega** [comment]
> @Universal-Omega Can you figure out the query we can run to see (a) which wikis had set any of these user rights to `*` and of those that did (b) a second query that removes the listed rights from `*`?

Yes, tomorrow or later tonight just merged this to prevent more in the meantime.

**Comment by dmehus** [comment]
> > @Universal-Omega Can you figure out the query we can run to see (a) which wikis had set any of these user rights to `*` and of those that did (b) a second query that removes the listed rights from `*`?
> 
> Yes, tomorrow or later tonight just merged this to prevent more in the meantime.

Okay, thanks. Can you DM me the list of wikis once you run it? I'm quite curious to know how many and which ones.

**Pull request merged**
