### PR TITLE
add ArticleFeedbackv5 for T847

### PR DESCRIPTION
**Pull request by ImBoPhil**

### CODE REVIEW

**Comment by LegoFan4000** [comment]
It seems to work. The only problem now is loads of undefined media wiki messages. 

    On Wednesday, October 12, 2016 2:34 PM, Reception123 <notifications@github.com> wrote:
 

 Merged #825.—

**Comment by Reception123** [comment]
@LegoFan4000 I think you commented on the wrong PR as this extension is only enabled on extloadwiki now.

**Comment by LegoFan4000** [comment]
No I mean I can see it working on ext load when I go there. It does indeed show up on the Main Page. 

    On Wednesday, October 12, 2016 2:48 PM, Reception123 <notifications@github.com> wrote:
 

 @LegoFan4000 I think you commented on the wrong PR as this extension is only enabled on extloadwiki now.—

**Comment by Reception123** [comment]
@ImBoPhil Please also add the .SQL files for ArticleFeedbackv5.

**Pull request merged**
