### PR TITLE
whitelist certain pages for cineastaswiki per T6230

### PR DESCRIPTION
**Pull request by Reception123**

### CODE REVIEW

**Review by RhinosF1 — CHANGES_REQUESTED** [review]
#L82 is listed as section for read whitelist changes, can we decide where things are going and either fix that order so it's not conflicting or put everything there?

**Comment by Reception123** [comment]
@RhinosF1 I've only seen a "Per-wiki overrides" section, and in that section I saw several whitelist read variables.

**Review by RhinosF1 — CHANGES_REQUESTED** [review]
Line 182

**Review by RhinosF1 — COMMENTED** [review]
Per discord, my comment to be addressed in seperate PR

**Pull request merged**
