### PR TITLE
drunkenpeasantswikiwiki settings

### PR DESCRIPTION
**Pull request by Reception123**
BLOCKED BY miraheze/puppet/issues/94

### CODE REVIEW

**Comment by JohnFLewis** [comment]
They want flow enabled on all pages, please add the relevant namespace occupy setting as well. (Unless it is default?)

**Comment by Reception123** [comment]
@JohnFLewis Not specified so I guess default.

**Comment by Reception123** [comment]
Added logo and favicon.

**Comment by JohnFLewis** [comment]
The default is nothing. They want it on all talk namespaces by default. You want wgFlowNamespadeOccupy to be set as well.

**Comment by Reception123** [comment]
How come there are many wikis that don't have any settings other than the default one? I'm not sure what to set for wgFlowNamespadeOccupy

**Comment by JohnFLewis** [comment]
Because not all wikis want it by default. There are several wikis there which have all talk namespaces enabled, just copy that configs.

**Comment by Reception123** [comment]
@JohnFLewis Done.

**Comment by Reception123** [comment]
@JohnFLewis @Southparkfan

**Pull request merged**
