### PR TITLE
add cmgi to except dorman policy

### PR DESCRIPTION
**Pull request by crutenmorg**
add one line

### CODE REVIEW

**Comment by Reception123** [comment]
@crutenmorg While this is good for after, A request at https://meta.miraheze.org/wiki/Stewards%27_noticeboard must be made first.

**Comment by crutenmorg** [comment]
@Reception123 but its not problem if put early in this commit?

**Comment by crutenmorg** [comment]
@Reception123 can I become member of WikiOpen in your organization?

**Comment by Reception123** [comment]
@crutenmorg Member of what? I'm not sure what you're referring to, but requesting it here is definitely not the right plac

**Pull request closed without merging**
