### PR TITLE
Add TemplateData and WikiEditor as required for TemplateWizard (T6517)

### PR DESCRIPTION
**Pull request by R4356th**
This should fix [T6517](https://phabricator.miraheze.org/T6517).

### CODE REVIEW

**Comment by paladox** [comment]
WikiEditor is a global extension.

**Comment by paladox** [comment]
https://github.com/miraheze/mw-config/blob/59624fc0ffe826a2352405776dac242b1e37a8ba/GlobalExtensions.php#L43

**Comment by R4356th** [comment]
Whoops! I doesn't it work for me then? Is there any necessary config?

**Comment by paladox** [comment]
@R4356th do you get an error?

**Comment by R4356th** [comment]
No.

**Pull request closed without merging**
