### PR TITLE
GeoData config for gratisdata

### PR DESCRIPTION
**Pull request by ugochimobi**
This is a follow-up of #4505. This PR gives us the proper way it should look like.

This is a lengthy array of each globe's parameters; they are the geographical entities on which the coordinate from GeoData is located. Having these arrays set and having #4535 set too will make them more effectual when using the {{#coordinates:}} parser function. Full explanation can be found on the extension page.

### CODE REVIEW

**Comment by RhinosF1** [comment]
@ugochimobi how does this meet @Universal-Omega's advice to explain your actions?

**Comment by ugochimobi** [comment]
> @ugochimobi how does this meet @Universal-Omega's advice to explain your actions?

Oops, I think I missed this one, let me update the original PR text field now.

**Comment by Universal-Omega** [comment]
Does `updateIndexGranularity.php` need ran if this is done still?

**Comment by Universal-Omega** [comment]
Does `updateIndexGranularity.php` need ran if this is done still?

**Comment by ugochimobi** [comment]
> Does `updateIndexGranularity.php` need ran if this is done still?

The extension page says that

**Comment by Universal-Omega** [comment]
> > Does `updateIndexGranularity.php` need ran if this is done still?
> 
> The extension page says that

This isn't changing `$wgGeoDataIndexGranularity` though, which is the only one the extension page says it needs ran for.

**Comment by ugochimobi** [comment]
> > > Does `updateIndexGranularity.php` need ran if this is done still?
> > 
> > 
> > The extension page says that
> 
> This isn't changing `$wgGeoDataIndexGranularity` though, which is the only one the extension page says it needs ran for.

That's true

**Pull request merged**
