### PR TITLE
Merge duplicate entries together

### PR DESCRIPTION
**Pull request by colleirose**
Didn't realize that two entries existed for genshinimpactwiki

### CODE REVIEW

**Comment by RhinosF1** [comment]
@coderabbitai is talking complete nonsense as far as I can tell

**Comment by RhinosF1** [comment]
@coderabbitai no, that's not what the PR does. This merges 2 entries for genshinimpactwiki into a single one which removes duplication which could behave unexpectedly.

**Comment by colleirose** [comment]
@coderabbitai The code you've provided is not accurate because it gives the impression that the code which disables MatomoAnalytics for `genshinimpactwiki` was removed from LocalWiki.php when that is not the case. This is the actual content of the `genshinimpactwiki` entry:

```php
	case 'genshinimpactwiki':
		$wgSpecialPages['Analytics'] = DisabledSpecialPage::getCallback( 'Analytics', 'MatomoAnalytics-disabled' );
		$wgMatomoAnalyticsDisableJS = true;
		$wgMatomoAnalyticsDisableCookie = true;

		$wgHooks['HtmlPageLinkRendererEnd'][] = 'onHtmlPageLinkRendererEnd';

		function onHtmlPageLinkRendererEnd(
			$linkRenderer,
			$target,
			$isKnown,
			&$text,
			&$attribs,
			&$ret
		) {
			if ( $isKnown ) {
				return true;
			}

			if ( $target->isExternal() ) {
				return true;
			}

			$attribs['rel'] = 'nofollow';

			return true;
		}

		break;
```

**Comment by RhinosF1** [comment]
@coderabbitai please edit your walkthrough and poem to reflect your learning in the later summaries

**Comment by colleirose** [comment]
Wait, why does it have a poem?

**Comment by colleirose** [comment]
@coderabbitai How do I disable your poem feature?

**Pull request merged**
