### PR TITLE
set wgPropertySuggesterMinProbability for gratisdatawiki

### PR DESCRIPTION
**Pull request by ugochimobi**
this sets how fast the suggestions should show up.

### CODE REVIEW

**Review by Universal-Omega — CHANGES_REQUESTED** [review]
Should be added to ManageWiki instead.

**Comment by ugochimobi** [comment]
> Should be added to ManageWiki instead.

It's currently not in ManageWiki, yoild you add it now?

**Comment by Universal-Omega** [comment]
> > Should be added to ManageWiki instead.
> 
> It's currently not in ManageWiki, yoild you add it now?

Yeah, what I'm saying is we could add it.

**Comment by ugochimobi** [comment]
> > > Should be added to ManageWiki instead.
> > 
> > 
> > It's currently not in ManageWiki, yoild you add it now?
> 
> Yeah, what I'm saying is we could add it.

Yeh I got you from the reply at #4622 💯

**Comment by Universal-Omega** [comment]
* #4665

**Pull request closed without merging**
