### PR TITLE
Add LogoFunctions (T6766)

### PR DESCRIPTION
**Pull request by R4356th**
Adds LogoFunctions per T6766. This should be merged with miraheze/mediawiki#1092.

### CODE REVIEW

**Review by Reception123 — CHANGES_REQUESTED** [review]
Everything else looks good, but it also needs to be added to LocalSettings.php under [this section](https://github.com/miraheze/mw-config/blob/master/LocalSettings.php#L789)

**Comment by R4356th** [comment]
> Everything else looks good, but it also needs to be added to LocalSettings.php under [https://github.com/miraheze/mw-config/blob/master/LocalSettings.php#L789](this section)

Yeah, I know and am doing that. :)

**Comment by Reception123** [comment]
> > Everything else looks good, but it also needs to be added to LocalSettings.php under [https://github.com/miraheze/mw-config/blob/master/LocalSettings.php#L789](this section)
> 
> Yeah, I know and am doing that. :)

Oh sorry, didn't know you weren't finished yet. My bad then

**Comment by R4356th** [comment]
This can be merged but the extension adds a configuration variable, ``$wgNamespaceLogos``, which needs namespace numbers (not constants) and I am not sure which type ManageWiki supports. It should be noted that there is an [upstream bug](https://phabricator.wikimedia.org/T234098) regarding logos being incorrectly set so we should consider if we want to add this to ManageWiki as well.

**Review by Universal-Omega — APPROVED** [review]

**Comment by Universal-Omega** [comment]
> This can be merged but the extension adds a configuration variable, `$wgNamespaceLogos`, which needs namespace numbers (not constants) and I am not sure which type ManageWiki supports. It should be noted that there is an [upstream bug](https://phabricator.wikimedia.org/T234098) regarding logos being incorrectly set so we should consider if we want to add this to ManageWiki as well.

All constants are are namespace numbers I think so both would probably work. But don't add it in the PR I will in another one. (To MWN)

**Comment by R4356th** [comment]
> > This can be merged but the extension adds a configuration variable, `$wgNamespaceLogos`, which needs namespace numbers (not constants) and I am not sure which type ManageWiki supports. It should be noted that there is an [upstream bug](https://phabricator.wikimedia.org/T234098) regarding logos being incorrectly set so we should consider if we want to add this to ManageWiki as well.
> 
> All constants are are namespace numbers I think so both would probably work. But don't add it in the PR I will in another one after I look into it first. (To MWN)

Okay. Sounds good. :)

**Review by Reception123 — APPROVED** [review]

**Pull request merged**
