### PR TITLE
Add DPE reasons

### PR DESCRIPTION
**Pull request by AgentIsai**

### CODE REVIEW

**Comment by Universal-Omega** [comment]
Any progress on this?

**Comment by AgentIsai** [comment]
> Any progress on this?

I forgot to mention but DPE reasons are completely broken. It won't hide the field if the "Exempt from Inactivity" box isn't clicked.

**Comment by 763499** [comment]
> > Any progress on this?
> 
> I forgot to mention but DPE reasons are completely broken. It won't hide the field if the "Exempt from Inactivity" box isn't clicked.

Oh. I'll try and fix that tomorrow.

**Comment by Universal-Omega** [comment]
This has conflicts

**Pull request merged**
