### PR TITLE
Update Wikibase.php

### PR DESCRIPTION
**Pull request by ugochimobi**

### CODE REVIEW

**Review by RhinosF1 — CHANGES_REQUESTED** [review]
Are any of these $wmg* set

**Comment by ugochimobi** [comment]
> Are any of these $wmg* set

Yes, they're set in LocalSettings.php

**Comment by ugochimobi** [comment]
But the PR hasn't been merged yet #4502

**Comment by RhinosF1** [comment]
See #4502

This isn't needed.

**Comment by ugochimobi** [comment]
I thought as much anyway

**Comment by ugochimobi** [comment]
Although, there are some configs that are now wmg, that needs to be set here....

**Pull request closed without merging**
