### PR TITLE
Merge 'master' into REL1_36

### PR DESCRIPTION
**Pull request by RhinosF1**
To be merged when rc0 is deployed.

### CODE REVIEW

**Comment by Universal-Omega** [comment]
Has merge conflicts.

**Comment by dmehus** [comment]
> Has merge conflicts.

I've already resolved the merge conflicts regarding my commit once. It's probably honestly easier for RhinosF1 to re-fork this repo then redo this PR, eh?

**Comment by RhinosF1** [comment]
> Has merge conflicts.

I'm not surprised but I'll deal with this when the time comes.

**Comment by Universal-Omega** [comment]
Merging this also to avoid future merge conflicts. It should fix it.

**Pull request merged**
