### PR TITLE
Userrights config for nycsubwaywiki

### PR DESCRIPTION
**Pull request by Amanda-Catherine**
Cleaner version of #5224

### CODE REVIEW

**Review by AgentIsai — APPROVED** [review]

**Comment by Amanda-Catherine** [comment]
@AgentIsai This doesn't seem to have worked.. the two user groups still exist.

**Comment by AgentIsai** [comment]
> This won't work. $wgConf can't be overriden like that or anywhere of ease. Just doesn't work like that from what I have experienced.

How can groups be unset then, at least for extensions?

**Comment by Amanda-Catherine** [comment]
That would just remove all the permissions from the groups, but the groups themselves would still be intact. I know it's possible to completely unset extension-defined groups, as I've done it before... but maybe the devs have changed something? Does anyone subscribe/contribute to the MediaWiki-I mailing list at WMF who could ask on the list?

**Comment by AgentIsai** [comment]
ManageWiki has changed an awful lot since you were last on Miraheze, Universal Omega has changed quite a few things so maybe that's why.

**Pull request merged**
