### PR TITLE
Remove metawiki configurations

### PR DESCRIPTION
**Pull request by AgentIsai**
Discussed with @Reception123 who approved the removal of the unnecessary meta tags and of the unneeded hardcoded Donation link on Meta.

### CODE REVIEW

**Comment by RhinosF1** [comment]
Is the sidebar link worth a heads up on AN? It's been there in various states on and off for 4 years afaics

**Review by RhinosF1 — APPROVED** [review]
Otherwise LGTM

**Comment by AgentIsai** [comment]
> Is the sidebar link worth a heads up on AN? It's been there in various states on and off for 4 years afaics

The plan was to readd it via MediaWiki:Sidebar once removed from here.

**Comment by RhinosF1** [comment]
> > Is the sidebar link worth a heads up on AN? It's been there in various states on and off for 4 years afaics
> 
> The plan was to readd it via MediaWiki:Sidebar once removed from here.

Cool, let me know when you need a merge

**Pull request merged**
