### PR TITLE
Add zhwp as import per T8281

### PR DESCRIPTION
**Pull request by CloakSelf**

### CODE REVIEW

**Review by RhinosF1 — CHANGES_REQUESTED** [review]
Syntax

**Review by RhinosF1 — CHANGES_REQUESTED** [review]
Still wrong

**Review by RhinosF1 — DISMISSED** [review]
Nope, still not right

**Comment by Universal-Omega** [comment]
> @CloakSelf Remove this line
> 
> ```
> 		'+zhwpwikiwiki' => [
> 			'zhwp',
> 		],
> 		
> 		],
> 		'+zhdelwiki' => [
> 			'zhwikipedia',
> 		],
> 	],
> ```
> 
> and replace it with
> 
> ```
> 		'+zhwpwikiwiki' => [
> 			'zhwp',
> 		],
> 		'+zhdelwiki' => [
> 			'zhwikipedia',
> 		],
> 	],
> ```
> 
> This should solve it.

that is still wrong, this messes up the syntax for the one above `zhwpwikiwiki`

**Comment by ugochimobi** [comment]
Oh well, please help us fix it

**Pull request merged**
