### PR TITLE
Add bureaucrat and consul protection/restriction level user rights to…

### PR DESCRIPTION
**Pull request by dmehus**
… testwiki

So Consuls can grant these protection/restriction level user rights to subordinate user groups as required

### CODE REVIEW

**Comment by RhinosF1** [comment]
Consensus?

**Comment by Universal-Omega** [comment]
They should be removed from $wgManageWikiPermissionsAdditionalRights if they are being added to $wgAvailableRights. The only difference is that with this, now they can be assigned via ManageWiki, whereas the ManageWiki config ones can't be.

**Comment by dmehus** [comment]
> Consensus?

Not needed. TestWiki operates on the basis of community discussions and Consul discretion.

**Comment by dmehus** [comment]
> They should be removed from $wgManageWikiPermissionsAdditionalRights if they are being added to $wgAvailableRights. The only difference is that with this, now they can be assigned via ManageWiki, whereas the ManageWiki config ones can't be.

That's fair. I didn't know that. I will add that. Thank you!

**Comment by RhinosF1** [comment]
> 

Is there any discussion on testwiki or indication of why now?

I don't see what subordinate group needs it.

**Comment by dmehus** [comment]
> > 
> 
> Is there any discussion on testwiki or indication of why now?
> 
> I don't see what subordinate group needs it.

`bot`, potentially, to allow approved bots to edit Consul-protected pages within their approved parameters. But the key is, Consuls would still be deciding which user groups should have it

**Comment by RhinosF1** [comment]
Is there a bot that needs it?

**Comment by Universal-Omega** [comment]
> > 
> 
> Is there any discussion on testwiki or indication of why now?
> 
> I don't see what subordinate group needs it.

This doesn't need discussion, I wouldn't think, it has no functional changes, as the restriction levels already exist, this only makes the rights available to assign in ManageWiki rather than a particular forced group, though now that I think about it, why? These rights won't be assigned to any groups besides the ones of the same name I think, which they already are.

**Comment by dmehus** [comment]
> Is there a bot that needs it?

In this case, yes, https://publictestwiki.com/wiki/TestWiki:Bot_approval_requests (@Agent-Isai's `bot`). This wouldn't grant any Consul user rights, other than the ability to edit Consul-protected pages, with the mandate approved by a Consul.

**Review by RhinosF1 — APPROVED** [review]
approved with my sysadmin hat and endorsed with my consul hat. (Some of those questions had a bit of both hats on)

**Review by Universal-Omega — APPROVED** [review]

**Pull request merged**
