### PR TITLE
Add Import Sources for batfamilywiki, batmanwiki and snapwikiwiki

### PR DESCRIPTION
**Pull request by R4356th**
Adds import sources for batfamilywiki, batmanwiki and snapwikiwiki. I am a bureaucrat on all these wikis.

### CODE REVIEW

**Comment by Universal-Omega** [comment]
As far as I'm aware this won't work for Fandom. Though could be wrong.

**Comment by R4356th** [comment]
@Universal-Omega, I could do something like-
```PHP
'wikia' => [
    'batman'
]
, if that is what you mean.

**Review by Universal-Omega — DISMISSED** [review]
batmanwikifandom is what I mean won't work

**Comment by R4356th** [comment]
But why? I have added it as a interwiki link locally.

**Comment by Universal-Omega** [comment]
> But why? I have added it as a interwiki link locally.

Because of Fandom's setup which blocks stuff like that

**Comment by R4356th** [comment]
Interwikis are a MediaWiki core feature. I do not think it is possible to block these.

**Comment by Universal-Omega** [comment]
> Interwikis are a MediaWiki core feature. I do not think it is possible to block these.

Fandom modifies core on their system significantly.

**Pull request merged**
