### PR TITLE
T9503: Enable IPInfo globally

### PR DESCRIPTION
**Pull request by AgentIsai**
To be merged once https://github.com/miraheze/puppet/pull/3120 is

### CODE REVIEW

**Comment by Universal-Omega** [comment]
This can't be done until after the 1.39 upgrade as well, as we have no way to test the extension on 1.38, which it needs tested first.

**Comment by AgentIsai** [comment]
> This can't be done until after the 1.39 upgrade as well, as we have no way to test the extension on 1.38, which it needs tested first.

That's unfortunate but understandable. Waiting another week won't work, especially since this has been pending since July.

**Comment by Universal-Omega** [comment]
Don't forget to blacklist the rights.

**Comment by AgentIsai** [comment]
> Don't forget to blacklist the rights.

Done

**Comment by Universal-Omega** [comment]
I will deploy tomorrow if no one does. But if deployed make sure to reset cache to make blacklist update. Otherwise blacklist wont update.

**Comment by AgentIsai** [comment]
Thanks

**Pull request merged**
