### PR TITLE
Better canned responses

### PR DESCRIPTION
**Pull request by R4356th**
Also fixes grammatical mistakes.

### CODE REVIEW

**Comment by Reception123** [comment]
Since there are some disagreements, there should probably be a wider discussion on the topic and we should make sure to include more canned responses for other situations as well.

**Comment by Reception123** [comment]
I also suggest we have the approval reasons first so that it can default to that when approving (so you don't have to search from the list if it's just a normal approval)

**Comment by R4356th** [comment]
This has not been marked as a draft for nothing. :)

**Review by dmehus — COMMENTED** [review]
All of these changes are positive and LGTM. Agree that "Approved as a non-exclusive, community-made and -run public wiki so described" includes redundant or duplicative phrasing that I probably should've revised a bit more. We don't need to say that the wiki was approved as a public wiki, for example, as that's made by clear by the other fields. If we can add a short comment reminding the new initial bureaucrat that wikis are run according to the collective, consensus-based decision-making of local wikis rather than the autocratic authority of the initial wiki requestor (which used to be called a "founder," I think), that'd be the only small-ish request I'd suggest to this draft PR.

**Comment by dmehus** [comment]
> I also suggest we have the approval reasons first so that it can default to that when approving (so you don't have to search from the list if it's just a normal approval)

That's fine, I'm fine with that. If possible, can we also indent the approval and decline reasons and insert unindented, greyed out "Approval reasons" and "Decline reasons" dividers, to differentiate the reasons in the drop-down box? Basically, like `MediaWiki:Delreason-dropdown`?

**Comment by dmehus** [comment]
> Since there are some disagreements, there should probably be a wider discussion on the topic and we should make sure to include more canned responses for other situations as well.

Well, the idea behind adding canned responses as an array is that any wiki creator could submit a pull request to add additional reasons at any time. We don't want to have duplicate reasons, but if there are other reasons which are having to be added as a comment too often or which don't fit the existing reasons, they can easily be added, just like we add CreateWiki categories from time to time.

**Review by Universal-Omega — APPROVED** [review]
I know it's still in draft, but this LGTM.

**Comment by R4356th** [comment]
> > I also suggest we have the approval reasons first so that it can default to that when approving (so you don't have to search from the list if it's just a normal approval)
> 
> That's fine, I'm fine with that. If possible, can we also indent the approval and decline reasons and insert unindented, greyed out "Approval reasons" and "Decline reasons" dividers, to differentiate the reasons in the drop-down box? Basically, like `MediaWiki:Delelereason-dropdown`?

I do not really get how that would be useful.

**Comment by dmehus** [comment]
> > > I also suggest we have the approval reasons first so that it can default to that when approving (so you don't have to search from the list if it's just a normal approval)
> > 
> > 
> > That's fine, I'm fine with that. If possible, can we also indent the approval and decline reasons and insert unindented, greyed out "Approval reasons" and "Decline reasons" dividers, to differentiate the reasons in the drop-down box? Basically, like `MediaWiki:Delelereason-dropdown`?
> 
> I do not really get how that would be useful.

Well, we don't have to do that in //this// PR as it //may// require a bit of extra coding, based on the discussions I've had with @Universal-Omega when we were discussing the original PR yesterday, it seemed like something that would be useful in terms of better arranging, rather than interfiling, the approval and decline reasons. Originally I envision having a conditional approval/decline reason field that would only list the approval //or// decline reasons depending on whether one selected "approve" or "decline". However, that might be too difficult or impossible to implement with the form types we have available to us, so as an alternative, I proposed "dividers" dividing the two separate types of reasons. The dividers themselves wouldn't be selectable options, obviously, and would just be meant as a tool, to //organize// the approval and decline reasons, which will be critically important as we //add// additional approve and decline reasons as the whole idea behind having the canned responses in an array was so that any wiki creator could request additional approve/decline reasons that would be used more than just one or two times.

**Comment by R4356th** [comment]
I think it is important to add functionality that allows Wiki Creators to add to (or even better, edit) the canned responses before submitting them so that they do not have to annoy requesters with another notification clarifying the response.

**Comment by dmehus** [comment]
> I think it is important to add functionality that allows Wiki Creators to add to (or even better, edit) the canned responses before submitting them so that they do not have to annoy requesters with another notification clarifying the response.

Well, there's no indication wiki requestors are annoyed by notifications, but I mean if that's easily doable, to be able to edit canned responses, we could possibly look at that; however, there was a dual purpose to the canned responses—better machine learning for the CreateWiki AI, so on that basis, I would favour non-editable standardized responses, which additional responses can be added to the array as needed and where frequently used, or additional comments can be added where the wiki creator desires to provide context-specific clarification or additional information.

**Comment by Reception123** [comment]
I do agree that once specific canned responses are implemented, they shouldn't really be edited, as that would set off the AI. If a wiki creator feels the need to add a comment, they are perfectly free to do so using the "Request comments" function that is offered. Additional canned responses can however be added if it's clear that there's a reoccurring response that isn't present in the current ones.

My preference would be that we don't rush the implementation of these canned responses and make sure that we all like the current ones and their wording, and also try to think of any others that might have to be added.

**Comment by R4356th** [comment]
I have marked this as ready for review but would appreciate waiting before merging this so that we can get more feedback.

**Comment by dmehus** [comment]
> > I do agree that once specific canned responses are implemented, they shouldn't really be edited, as that would set off the AI. If a wiki creator feels the need to add a comment, they are perfectly free to do so using the "Request comments" function that is offered. Additional canned responses can however be added if it's clear that there's a reoccurring response that isn't present in the current ones.
> 
> Something this feature is missing is the ability to add text as needed. I would like to be able to tell the requester how to edit the request to add more info when needed, for example.

Perhaps that could be an additional field, or the ability to add a comment from the "handle request" screen, but I wouldn't want to make the approval/decline reasons editable for the reason(s) articulated above.

> > My preference would be that we don't rush the implementation of these canned responses and make sure that we all like the current ones and their wording, and also try to think of any others that might have to be added.
> 
> I suggest sending a mass message to all Wiki Creators asking for feedback before merging this.

I mean, we _could_, but that seems to me to bit overkill, as many wiki creators are not that active. The idea is that these canned responses are not set in stone so if wiki creators have reasonable changes after merging, we can make minor modifications to the phrasing or add additional reasons as needed.

**Comment by Universal-Omega** [comment]
I agree with both point a views. So it all comes down to which one's benefits outweigh the other's. For one, the uneditable CannedResponses provides a better AI, which is a huge benefit. But on the other-hand, unless all the replies are 100% sufficient for every single possible approve or decline reason, it could lead to confusing the requester when requests are declined. It also seems like Echo notification emails for CreateWiki already don't work, which already makes things more confusing about the status of their request. This may only add to the confusion at times, although I see the benefits for doing CannedResponses significantly more valuable in the long-term. AI being more accurate is a huge benefit, and I don't see a reason, at this time to sacrifice AI for editable CannedResponses. Eventually this may have to be reconsidered if things become confusing for creators or requester. However for now I think the way to move forward is implementing this how it is now. Also in regards to emailing creators, as mentioned by @R4356th above, I find that unnecessary. Reason being that creators know where they are doing, for the most part. They will understand the changes once they see them. I don't think we need to email everyone right now unless we get to many questions.

Also one final point I do want to raise is that some wiki creators use non-English replies to make replies more accurate to what language the requester used. This would force all decline/approve comment to be English, which may not be the best idea. We could localise the options, but that also may completely go against the whole point of this, and interfere with AI just as customisable replies would.

**Comment by dmehus** [comment]
> I strongly disagree. There are some who hop in when the regulars are inactive for some reason. If you could give a strong reason against sending messages to all Wiki Creators, we could send those to the active and semi-active ones.

Well, I just know that in the past, whenever we've made changes to CreateWiki, including the RequestWiki UI, we've not involved every wiki creator in potential changes. Those that have been interested have shared their input on the relevant Phabricator task or GitHub pull request, as we're doing now.

I'm not opposed to a mass message, but I think we should save that for _after_ the changes are implement, to advise wiki creators of some changes to the approval/decline workflow, how to additional comments as they may deem necessary, how to suggest changes to existing canned responses, or propose new canned messages, all of that sort of thing.

We just need to be mindful not to intrude on their talk pages _too_ often, and one message notifying them of this pull request and one message notifying them of the changes having been implemented would seem to me to be a bit excessive.

**Comment by R4356th** [comment]
> In regards to @R4356th's idea in messaging wiki creators, I currently find that unnecessary. Reason being that creators know where they are doing, for the most part. They will understand the changes once they see them. I don't think we need to message everyone right now unless we get to many questions. Overall, needing to message wiki creators for this is basically calling them incompetent. Wiki creators wouldn't be wiki creators if they were. They will end up figuring the changes out, and there have been larger changes before, and they figured it out. They will again. If we really need to, we can later.

I believe you and @dmehus have misunderstood my reasoning for mass messaging WCs. I want their feedback on these responses so that we know there is consensus as many are not aware of this PR and may want to suggest changes as well as additions.

> Well, I just know that in the past, whenever we've made changes to CreateWiki, including the RequestWiki UI, we've not involved every wiki creator in potential changes. Those that have been interested have shared their input on the relevant Phabricator task or GitHub pull request, as we're doing now.

Please view the relevant [log](https://meta.miraheze.org/wiki/Special:Log/massmessage).

> We just need to be mindful not to intrude on their talk pages too often, and one message notifying them of this pull request and one message notifying them of the changes having been implemented would seem to me to be a bit excessive.

I am only suggesting one message. There is no need to bother everyone with a message after merging this.

**Comment by dmehus** [comment]
> Please view the relevant [log](https://meta.miraheze.org/wiki/Special:Log/massmessage).

Right, and I did, and that announcement was a notification of a change to the RequestWiki UI. I can't remember if it was posted _before_ or _after_, but in any case, it was mainly to notify wiki creators of a change, or changes even, to the RequestWiki UI that would affect their workflow. It wasn't intended to solicit feedback or establish a wider consensus.

We're all happy with your modifications and additions to the canned responses. Even after they're merged, they're not carved in stone, and we'll always review and accept any proposed minor modifications to the canned responses, or even to adding additional messages when there's a need.

**Comment by Reception123** [comment]
I personally think it would make more sense if we used MassMessage _after_ the changes are adopted in order to inform wiki creator's of the changes. If we want to get feedback, I feel that it would make more sense to make a post on CN.

**Comment by dmehus** [comment]
I've opened a pull request (https://github.com/R4356th/mw-config/pull/2) on @R4356th's branch with some minor modifications to phrasing and one duplicate wiki reason. I'm open to re-adding the duplicate wiki reason, but it needs some rephrasing, as we've always allowed wikis sharing the same topic(s) to exist. We just don't permit, generally speaking, wikis that are complete or substantial carbon copies of existing wikis.

**Comment by R4356th** [comment]
> I personally think it would make more sense if we used MassMessage _after_ the changes are adopted in order to inform wiki creator's of the changes. If we want to get feedback, I feel that it would make more sense to make a post on CN.

Sure, I am fine with that as that would hopefully help us get feedback from the wider community.

**Comment by WhatDoYaDoWithADrunkenSailor** [comment]
What will we do with a drunken sailor?
What will we do with a drunken sailor?
What will we do with a drunken sailor?
Early in the mornin'

Way hay and up she rises
Way hay and up she rises
Way hay and up she rises
Early in the mornin'

Shave his belly with a rusty razor
Shave his belly with a rusty razor
Shave his belly with a rusty razor
Early in the mornin'

Way hay and up she rises
Way hay and up she rises
Way hay and up she rises
Early in the mornin'

Put him in a long boat 'til he's sober
Put him in a long boat 'til he's sober
Put him in a long boat 'til he's sober
Early in the mornin'

Way hay and up she rises
Way hay and up she rises
Way hay and up she rises
Early in the mornin'

Stick him in the scupper with a hosepipe on him
Stick him in the scupper with a hosepipe on him
Stick him in the scupper with a hosepipe on him
Early in the mornin'

Way hay and up she rises
Way hay and up she rises
Way hay and up she rises
Early in the mornin'

Put him in the bed with the captain's daughter
Put him in the bed with the captain's daughter
Put him in the bed with the captain's daughter
Early in the mornin'

Way hay and up she rises
Way hay and up she rises
Way hay and up she rises
Early in the mornin'

That's what we do with a drunken sailor
That's what we do with a drunken sailor
That's what we do with a drunken sailor
Early in the mornin'

Way hay and up she rises
Way hay and up she rises
Way hay and up she rises
Early in the mornin'

Way hay and up she rises
Way hay and up she rises
Way hay and up she rises
Early in the mornin'What will we do with a drunken sailor?
What will we do with a drunken sailor?
What will we do with a drunken sailor?
Early in the mornin'

Way hay and up she rises
Way hay and up she rises
Way hay and up she rises
Early in the mornin'

Shave his belly with a rusty razor
Shave his belly with a rusty razor
Shave his belly with a rusty razor
Early in the mornin'

Way hay and up she rises
Way hay and up she rises
Way hay and up she rises
Early in the mornin'

Put him in a long boat 'til he's sober
Put him in a long boat 'til he's sober
Put him in a long boat 'til he's sober
Early in the mornin'

Way hay and up she rises
Way hay and up she rises
Way hay and up she rises
Early in the mornin'

Stick him in the scupper with a hosepipe on him
Stick him in the scupper with a hosepipe on him
Stick him in the scupper with a hosepipe on him
Early in the mornin'

Way hay and up she rises
Way hay and up she rises
Way hay and up she rises
Early in the mornin'

Put him in the bed with the captain's daughter
Put him in the bed with the captain's daughter
Put him in the bed with the captain's daughter
Early in the mornin'

Way hay and up she rises
Way hay and up she rises
Way hay and up she rises
Early in the mornin'

That's what we do with a drunken sailor
That's what we do with a drunken sailor
That's what we do with a drunken sailor
Early in the mornin'

Way hay and up she rises
Way hay and up she rises
Way hay and up she rises
Early in the mornin'

Way hay and up she rises
Way hay and up she rises
Way hay and up she rises
Early in the mornin'

**Comment by Reception123** [comment]
The "none of the above" addition really does basically bring us back to the "Other" free-form option that was debated at the beginning and rejected. That's why this PR is being kept open so long, so we try to think of as many possibilities as possible. This is also why the reasons shouldn't be too specific, so they can encompass different situations.

**Comment by dmehus** [comment]
> The "none of the above" addition really does basically bring us back to the "Other" free-form option that was debated at the beginning and rejected. That's why this PR is being kept open so long, so we try to think of as many possibilities as possible. This is also why the reasons shouldn't be too specific, so they can encompass different situations.

Yeah, I mean, I _do_ get the idea behind it, but like the canned responses, the _Purposes_ field was always designed to be a _dynamic_ field, with additional purpose(s) added periodically. That's not to say we should be adding new purposes every week or so something like that, as the CreateWiki AI _does_ learn from approved and declined wiki requests; however, if after sufficiently clarifying the purpose of the wiki with the requestor, we still don't have a clear _purpose_ for the wiki, then we should be adding an additional purpose to the array. Or, alternatively, we could have an _Other (please see the custom purpose in the "Request comments" tab)_ option (though this wouldn't be my first preference.

As another matter, I also do not like how _Alternate history wiki_ was set up as the default option by virtue of it being first in the list. I believe the first listed option should be a _(blank)_ option and if the wiki requestor does _not_ specify a purpose for their wiki, then their wiki request does not go into the request wiki queue.

**Comment by R4356th** [comment]
> The "none of the above" addition really does basically bring us back to the "Other" free-form option that was debated at the beginning and rejected. That's why this PR is being kept open so long, so we try to think of as many possibilities as possible. This is also why the reasons shouldn't be too specific, so they can encompass different situations.

How is this even relevant here? Would this harmfully impact AI? Don't you think it makes no sense to presume we have all the purposes of the wiki available? Why was the purposes feature even added?

**Comment by dmehus** [comment]
> > The "none of the above" addition really does basically bring us back to the "Other" free-form option that was debated at the beginning and rejected. That's why this PR is being kept open so long, so we try to think of as many possibilities as possible. This is also why the reasons shouldn't be too specific, so they can encompass different situations.
> 
> How is this even relevant here? Would this harmfully impact AI? Don't you think it makes no sense to presume we have all the purposes of the wiki available? Why was the purposes feature even added?

It was added to better encapsulate the purpose of the wiki. It can be edited by wiki creators, where needed, but ideally should be selected for the requestor. The purpose doesn't have to fit _exactly_; idea is to select the purpose that most closely encapsulates the wiki request. Secondarily, having these preformatted purposes will help improve the CreateWiki's AI. If we need any additional purposes, though many of the existing purposes can be used to fit nearly all wikis. There might just be several more we need. Description is intended to both provide a more detailed purpose and articulate the scope of the wiki / type of content the wiki proposes to write about.

**Comment by Universal-Omega** [comment]
Merging per discussion with @R4356th, @dmehus, and @Reception123.

**Pull request merged**
