### PR TITLE
T12526: Add redundent langs to DisabledLanguages on meta

### PR DESCRIPTION
**Pull request by pixDeVl**

### CODE REVIEW

**Comment by Universal-Omega** [comment]
What is the reason this is a draft? Is it blocked on something?

**Comment by pixDeVl** [comment]
The task was stalled but I can’t recall what right now lmao. Maybe deleting the rest of the translations? Let me see

**Comment by clarfonthey** [comment]
I believe that this only disables adding new translations, and you could in theory merge this and delete the translations later. Would have to verify in the code, though.

Either way, since the translate extension actually writes translations to pages instead of just caching them, I'm 90% sure it should be fine to merge first and delete later.

**Comment by winstonsung** [comment]
@AgentIsai :

There are still remaining CNBanner pages not migrated.

Screenshot

**Comment by winstonsung** [comment]
Remaining migration done, could re-apply:

* <https://meta.miraheze.org/wiki/Special:ActiveLanguages/zh>
* <https://meta.miraheze.org/wiki/Special:ActiveLanguages/zh-cn>
* <https://meta.miraheze.org/wiki/Special:ActiveLanguages/zh-tw>

**Pull request merged**
