### PR TITLE
Re-do request #1111

### PR DESCRIPTION
**Pull request by KatieKoder123**
Re-do request #1111 

I know that everything is supposed to be in alphabetical order, but does it really break anything if they aren't? Also, I have granted bureaucrat the ability to add founder so that I can add myself, but this will be removed after I am in the founder group.

### CODE REVIEW

**Comment by DeltaQuad-DQ** [comment]
Sorry, that's my alternate account. I confirm that this still belongs to Amanda.

**Comment by DeltaQuad-DQ** [comment]
Ahem... could someone please check and merge this? @Reception123 @Southparkfan @JohnFLewis

**Comment by DeltaQuad-DQ** [comment]
@JohnFLewis the configuration changes didn't work on either PR

**Comment by Reception123** [comment]
@DeltaQuad-DQ It takes ~10 minutes for the changes to go into effect after a PR is merged (the time puppet runs)

**Comment by DeltaQuad-DQ** [comment]
Oh, thanks @Reception123

**Comment by DeltaQuad-DQ** [comment]
@JohnFLewis @Southparkfan @NDKilla I need a steward to add me into the founder group on elements.miraheze.org - I thought I granted bureaucrats the ability to add the group, but it seems that I didn't.

**Comment by Reception123** [comment]
@DeltaQuad-DQ I will check that out. Also please don't ping people, we are subscribed to this PR and will see any messages you send

**Comment by Reception123** [comment]
@DeltaQuad-DQ You're now in the founder group

**Comment by DeltaQuad-DQ** [comment]
Success! Thanks

**Pull request merged**
