### PR TITLE
Add certain UW configurations to lhmnwiki

### PR DESCRIPTION
**Pull request by songnguxyz**

### CODE REVIEW

**Comment by RhinosF1** [comment]
Why has another wiki been removed?

**Comment by RhinosF1** [comment]
Note to review:
- is there a DoS risk from user input against preg_match
- Is this parsoid compatible

**Comment by songnguxyz** [comment]
> Note to review:
> 
>     * is there a DoS risk from user input against preg_match
> 
>     * Is this Parsoid compatible

This is the code given by the MediaWiki page for the extension ([here](https://www.mediawiki.org/wiki/Extension:UploadWizard#Modifying_file_pages_created_by_Upload_Wizard))

> Why has another wiki been removed?

It's one of the closed wikis I owned before, it's a wiki with the Incubator style and extensions.

**Comment by RhinosF1** [comment]
> > Note to review:
> > ```
> > * is there a DoS risk from user input against preg_match
> > 
> > * Is this Parsoid compatible
> > ```
> 
> This is the code given by the MediaWiki page for the extension ([here](https://www.mediawiki.org/wiki/Extension:UploadWizard#Modifying_file_pages_created_by_Upload_Wizard))
That doesn't mean I trust the code or it's up to date and future proof.
> > Why has another wiki been removed?
> 
> It's one of the closed wikis I owned before, it's a wiki with the Incubator style and extensions. (I know it is not the best practice out there, but to clean up old code from my abandoned project)

Please do that in a separate PR. PRs shouldn't be doing multiple things.

**Comment by songnguxyz** [comment]
> > > Note to review:
> > > ```
> > > * is there a DoS risk from user input against preg_match
> > > 
> > > * Is this Parsoid compatible
> > > ```
> > 
> > 
> > This is the code given by the MediaWiki page for the extension ([here](https://www.mediawiki.org/wiki/Extension:UploadWizard#Modifying_file_pages_created_by_Upload_Wizard))
> 
> That doesn't mean I trust the code or it's up to date and future proof.
> 
> > > Why has another wiki been removed?
> > 
> > 
> > It's one of the closed wikis I owned before, it's a wiki with the Incubator style and extensions. (I know it is not the best practice out there, but to clean up old code from my abandoned project)
> 
> Please do that in a separate PR. PRs shouldn't be doing multiple things.

I will close the PR in response to the comments as it took me too long to get it right. Expect a new one with only the UW settings.

**Pull request closed without merging**
