### PR TITLE
remove cologne blue

### PR DESCRIPTION
**Pull request by RhinosF1**
no longer maintained

### CODE REVIEW

**Comment by RhinosF1** [comment]
oops, forgot about that branch when cleaning my repo

**Comment by Reception123** [comment]
what is this waiting on?

**Comment by RhinosF1** [comment]
Operations approval

**Comment by PlavorSeol** [comment]
https://phabricator.wikimedia.org/T115430#1724958

**Comment by RhinosF1** [comment]
Per @PlavorSeol, this is now pointless due to them being taken over.

**Pull request closed without merging**
