### PR TITLE
add Kartographer config to ManageWiki

### PR DESCRIPTION
**Pull request by ugochimobi**
wgKartographerStaticMapframe and wgKartographerEnableMapFrame

### CODE REVIEW

**Review by Universal-Omega — CHANGES_REQUESTED** [review]
Needs LS also

**Comment by ugochimobi** [comment]
@Universal-Omega Done

**Review by Universal-Omega — CHANGES_REQUESTED** [review]
Alphabetical LS please.

**Comment by ugochimobi** [comment]
Welp, I had to do a total re-ordering, I used `wgKartographer` as a common factor.

**Review by Universal-Omega — APPROVED** [review]

**Pull request merged**
