### PR TITLE
On hold reason

### PR DESCRIPTION
**Pull request by dmehus**
As suggested by @Agent-Isai

### CODE REVIEW

**Comment by Universal-Omega** [comment]
We also have "On hold pending response" so maybe make the display text more clear for this one?

**Review by AgentIsai — APPROVED** [review]

**Comment by dmehus** [comment]
> We also have "On hold pending response" so maybe make the display text more clear for this one?

Done. Should we maybe move that reason to the "on hold" reasons also?

**Comment by AgentIsai** [comment]
Maybe the on hold reasons should be moved between the approval and decline reasons for better visibility

**Comment by dmehus** [comment]
> Maybe the on hold reasons should be moved between the approval and decline reasons for better visibility

We //could//, but since there isn't really multiple sections, arguably, the visibility would be better at the bottom? What I originally wanted was to add greyed out lines, which //can't// be selected, for the section dividers, but I'm not sure how to do that. Maybe @Universal-Omega can make that change to CreateWiki after the merge?

**Comment by Universal-Omega** [comment]
Ready to be merged then?

**Comment by dmehus** [comment]
> Ready to be merged then?

I'm okay with it. Do you know what I mean about the suggestion after the merge?

**Comment by Universal-Omega** [comment]
> > Ready to be merged then?
> 
> I'm okay with it. Do you know what I mean about the suggestion after the merge?

Yes, I will look in a few days.

**Comment by dmehus** [comment]
> > > Ready to be merged then?
> > 
> > 
> > I'm okay with it. Do you know what I mean about the suggestion after the merge?
> 
> Yes, I will look in a few days.

Thanks! :)

**Pull request merged**
