### PR TITLE
Disable Anonymous Editions in "paddelnwiki" for T2325

### PR DESCRIPTION
**Pull request by AlvaroMolinaCL**
Disable Anonymous Editions in "paddelnwiki" for Phabricator Task [T2325](https://phabricator.miraheze.org/T2325). Thanks.

### CODE REVIEW

**Comment by MacFan4000** [comment]
This is incorrectly done. While this would work, editing should usually be restricted using wmgEditingMatrix. So you would add an entry for said wiki with the anon option set to true.

**Comment by AlvaroMolinaCL** [comment]
@MacFan4000: Is it possible that you can do it? Right now I'm busy, I've enabled the option so you can also edit the file.

**Comment by MacFan4000** [comment]
I’ll make a new pull request.

**Comment by MacFan4000** [comment]
Redone in #1785

**Pull request closed without merging**
