### PR TITLE
Propose more extensions

### PR DESCRIPTION
**Pull request by kenng69**
I want to propose more file extensions in the File Extension settings.

### CODE REVIEW

**Comment by RhinosF1** [comment]
Can someone from Operations check that all these files are safe to be added to the list?

**Comment by RhinosF1** [comment]
Can you also ensure that you _need_ all of these please @kenng69 ?

**Comment by Reception123** [comment]
I disagree with some of them such as .bin

**Comment by Pix1234** [comment]
I'm boldly closing this PR because theres not been any active discussion, and I don't see anyone agreeing for this to be merged.

**Pull request closed without merging**
