### PR TITLE
Enable refreshed on ATT for T901

### PR DESCRIPTION
**Pull request by LegoFan4000**

### CODE REVIEW

**Comment by JohnFLewis** [comment]
bad syntax

**Comment by Reception123** [comment]
I'm not sure if this will cause errors or not, or what the status of the extension is so I will let someone else merge this.

**Comment by LegoFan4000** [comment]
@Reception123 it does work if you go to https://applewiki.tk/w/index.php?title=Main_Page&useskin=refreshed

**Comment by LegoFan4000** [comment]
John and I worked it out last night.

**Pull request merged**
