### PR TITLE
Installing GlobalUsage extension

### PR DESCRIPTION
**Pull request by examknow**
Installing GlobalUsage extension per Phabricator item T4990

### CODE REVIEW

**Comment by examknow** [comment]
This will need to be made global per comment from @JohnFLewis

**Comment by examknow** [comment]
Everything should be fixed now.

**Comment by examknow** [comment]
GlobalUsage is now enabled automatically by the system **only** when $wgMirahezeCommons is true and $cwPrivate is false.

**Comment by RhinosF1** [comment]
Is anyone working on this?

**Comment by Reception123** [comment]
@RhinosF1 Well I just wanted Paladox to help in case something goes wrong but anyone can try to do it.

**Comment by paladox** [comment]
You can proceed whenever.

**Pull request merged**
