### PR TITLE
Fix contactpage extension name

### PR DESCRIPTION
**Pull request by Universal-Omega**

### CODE REVIEW

**Comment by paladox** [comment]
Why remove that piece of information?

**Comment by Universal-Omega** [comment]
> Why remove that piece of information?

Because it does not look right. If you think it is fine to keep it, we can, but it just seemed inconstant to me.

**Comment by paladox** [comment]
Seems fine to me, let's people know they must set it.

**Comment by JohnFLewis** [comment]
> Seems fine to me, let's people know they must set it.

Why for this extension and not for all the other extensions that have similar required configurations or even just configurations?

**Comment by paladox** [comment]
> > Seems fine to me, let's people know they must set it.
> 
> Why for this extension and not for all the other extensions that have similar required configurations or even just configurations?

oh good question. I guess we can merge this then to follow the standard we've done for all the other extensions.

**Pull request merged**
