### PR TITLE
T12146: Add CustomSubtitle

### PR DESCRIPTION
**Pull request by BlankEclair**
(This PR is untested)

## Summary by CodeRabbit

- **New Features**
  - Introduced the `CustomSubtitle` extension to enhance subtitle customization options for your wiki pages. 
  - Easily access the extension details via the provided link page.

### CODE REVIEW

**Comment by redbluegreenhat** [comment]
With the release date of 1.42 pushed forward, I'll be going ahead with this install by this weekend

**Review by redbluegreenhat — APPROVED** [review]

**Comment by redbluegreenhat** [comment]
@BlankEclair extension is installed and working.

**Comment by BlankEclair** [comment]
Oddly enough, even though it's visible and enabled on [ManageWiki/extensions](https://rainverse.wiki/wiki/Special:ManageWiki/extensions), it's not working ([example](https://rainverse.wiki/wiki/User:BlankEclair/Sandbox/CustomSubtitle)) or visible on [Special:Version](https://rainverse.wiki/wiki/Special:Version).

**Comment by BlankEclair** [comment]
Interestingly, the [server admin log](https://meta.miraheze.org/wiki/Tech:Server_admin_log) has 8 entries from test151 and 18 entries from mwtask181, but only 2 from mwtask171 (which I believe are automatic config pulls from Puppet).

(Also, I tried to poke mw181 using [X-Miraheze-Debug](https://meta.miraheze.org/wiki/Tech:Varnish#X-Miraheze-Debug), but the x-served-by header didn't say it was from mw181)

**Comment by redbluegreenhat** [comment]
> Interestingly, the [server admin log](https://meta.miraheze.org/wiki/Tech:Server_admin_log) has 8 entries from test151 and 18 entries from mwtask181, but only 2 from mwtask171 (which I believe are automatic config pulls from Puppet).

That was me trying to find out a way for mwdeploy to _only_ touch the extension folder, I couldn't follow the regular way of doing it this time.

Extension works just fine in testing (https://test.mirabeta.org/wiki/User:BlueMoon/cs), maybe I skipped something on prod.

**Comment by redbluegreenhat** [comment]
@BlankEclair it's working now. Indeed, I had skipped a step https://meta.miraheze.org/wiki/Tech:Server_admin_log?diff=prev&oldid=401768

**Pull request merged**
