### PR TITLE
Disable deletion protection on WikiCanada

### PR DESCRIPTION
**Pull request by Amanda1234567**
Pointless, as only sysops can delete pages anyway

### CODE REVIEW

**Comment by Amanda1234567** [comment]
@JohnFLewis @Reception123 why did Travis-CI fail?

**Comment by revi** [comment]
>1.07s$ bash .travis.phplint.sh
>PHP Parse error:  syntax error, unexpected ';', expecting ')' in ./LocalSettings.php on line 4582
>Errors parsing ./LocalSettings.php

When you read the log, it says everything you need to fix.

**Comment by Amanda1234567** [comment]
@revi I have no idea what that technical junk means

**Comment by revi** [comment]
Basically it's expected that you read the logs when it fails: you can ignore it when ticks are ✓, but when ticks are not ✓, you're supposed to read the logs, and fix them apporpriately.

As a courtesy: PHP is complaining about having `;` on end of line 4582, where it expected `)`.

**Comment by The-Voidwalker** [comment]
easy fix, remove the last two characters on line 4582
should look like:
`'wikicanadawiki' => array();`

**Comment by Amanda1234567** [comment]
@revi @The-Voidwalker fixed

**Pull request merged**
