### PR TITLE
Usawiki: create special user group for Miraheze staff

### PR DESCRIPTION
**Pull request by AgraveBanks**

### CODE REVIEW

**Comment by Reception123** [comment]
These permissions cannot be used by normal wikis as Miraheze is a wiki farm. Only stewards have access to these permissions.

**Comment by AgraveBanks** [comment]
@Reception123 this "staff" group would be taking the place of the "steward" group locally on usawiki. I wouldn't have access to it - only users with the 'userrights-interwiki' permission (stewards and sysadmins) would be able to add themselves to the group.

**Comment by AgraveBanks** [comment]
@Reception123 if you look at Special:ListGroupRights on usawiki, you'll see that the "steward" group has the CentralAuth permissions and that there are "checkuser" and "oversight" groups as well. All I'm doing is merging the three groups into one and adding the "renameuser" permission to it.

**Comment by Reception123** [comment]
@AgraveBanks Ok. Please call the entire permission "steward", though.

**Comment by AgraveBanks** [comment]
@Reception123 done. Please also merge the other PR that you closed, because that one unset the "oversight" and "checkuser" groups so that the permissions would not be in two places. In addition, I want to unset the default "steward" group and replace it with this one so that I can create a custom project page for "stewards". Currently, the "steward" link in Special:ListGroupRights soft-redirects to the Meta policy.

**Comment by labster** [comment]
PR by a ban evader. Closing PR.

**Pull request closed without merging**
