### PR TITLE
add 8station wiki by-nc-sa license url per req

### PR DESCRIPTION
**Pull request by Reception123**

### CODE REVIEW

**Comment by Wynter** [comment]
Should https:// be used instead?

**Comment by Reception123** [comment]
yes indeed @Wynter , thanks. The link was given with http so I forgot to change it.

**Comment by revi** [comment]
If you are changing URL, why not logo and texts?

**Comment by Reception123** [comment]
@revi I would but I don't know where to find the logo

**Comment by revi** [comment]
- Go to [CCL license choose](https://creativecommons.org/choose/)
 - Choose NC/SA
 - You see the [logo](https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png), voila!

I do not guarantee about the size. You should do the job by yourself.

**Comment by Reception123** [comment]
will reopen when i gather and fix all info

**Pull request closed without merging**
