### PR TITLE
Add testwikiwiki to loginwiki's import sources

### PR DESCRIPTION
**Pull request by dmehus**
Required for transwiki imports on Loginwiki

### CODE REVIEW

**Review by RhinosF1 — COMMENTED** [review]
Has anyone requested this for a specific purpose?

**Comment by dmehus** [comment]
> Has anyone requested this for a specific purpose?

Me.

**Comment by RhinosF1** [comment]
Fair enough.

Do we know if testwikiwiki has been privacy reviewed? (Not that I don't trust @MacFan4000 )

I'm not entirely sure how this works with cross-wiki interaction and whether it would allow access to PII when it imports.

**Comment by dmehus** [comment]
> Fair enough.
> 
> Do we know if testwikiwiki has been privacy reviewed? (Not that I don't trust @MacFan4000 )
> 
> I'm not entirely sure how this works with cross-wiki interaction and whether it would allow access to PII when it imports.

I don't see why the privacy policy would come in to play. That's never been a requirement to check for adding transwiki import sources. I'm not requesting that `testwiki.wiki` be added to the CSP whitelist; this is //just// for importing templates as needed.

**Review by RhinosF1 — APPROVED** [review]
Logic in https://github.com/wikimedia/mediawiki/blob/5357695270161bce1f6dbaccc96645791f17a013/includes/import/ImportStreamSource.php#L114 definately doesn't pass any user info when doing the import so \o/

**Review by Universal-Omega — APPROVED** [review]

**Pull request merged**
