### PR TITLE
Remove Widgets extension

### PR DESCRIPTION
**Pull request by Universal-Omega**

### CODE REVIEW

**Review by RhinosF1 — APPROVED** [review]

**Review by paladox — APPROVED** [review]

**Review by Pix1234 — APPROVED** [review]
Make sure to remove puppet per paladox

**Review by JohnFLewis — APPROVED** [review]

**Comment by Universal-Omega** [comment]
> Make sure to remove puppet per paladox

https://github.com/miraheze/puppet/pull/1571

**Review by NDKilla — APPROVED** [review]
I don't even agree with this requiring so many reviews, but here's my +1

**Review by Reception123 — APPROVED** [review]

**Review by Southparkfan — APPROVED** [review]
Granted that we will help wikis to find alternative solutions for Widgets.

**Comment by Universal-Omega** [comment]
With all sysadmins approving this. I'm going ahead with removing the widgets Extension.

**Pull request merged**
