### PR TITLE
Allow removal of restricted groups on Elements Wiki

### PR DESCRIPTION
**Pull request by DeltaQuad-DQ**
This would not allow me to access these groups, nor assign them to myself or anyone else. However, it would allow me to remove them in an emergency situation should a steward attempt to perform an unauthorized action on my wiki with them.

### CODE REVIEW

**Comment by Southparkfan** [comment]
I do not see how a wiki policy should be able to require founder approval for any of these actions (assigning/using CU/OS/steward rights).

I will let other people comment on this, though.

**Comment by DeltaQuad-DQ** [comment]
@Southparkfan please see https://elements.miraheze.org/wiki/Elements:Privacy policy#CheckUser and https://elements.miraheze.org/wiki/Elements:Consensus_is_required

**Comment by DeltaQuad-DQ** [comment]
@Southparkfan @JohnFLewis @NDKilla @Reception123 What is the status of this? Do any of you have additional comments/questions?

**Comment by DeltaQuad-DQ** [comment]
HELLO?? What is the status of this?

**Comment by revi** [comment]
Please note that lack of response for merely 24hr is acceptable when it's non-breaking.

**Comment by DeltaQuad-DQ** [comment]
@JohnFLewis can you please assign one or more of these rights to yourself on my wiki, but do not do anything with them? I want to test this change and make sure it works.

**Comment by Southparkfan** [comment]
You should really stop pinging people if it's not an emergency. Thank you.

**Pull request merged**
