### PR TITLE
Split "Tabber" and "Tabs" extensions

### PR DESCRIPTION
**Pull request by Universal-Omega**

### CODE REVIEW

**Review by RhinosF1 — APPROVED** [review]
As long as existing users aren't impacted (obviously this requires you manually moving them).

**Comment by PullRequestMaster** [comment]
> As long as existing users aren't impacted (obviously this requires you manually moving them).

How did you approve changes? I am confused on how to do that

**Comment by RhinosF1** [comment]
> > As long as existing users aren't impacted (obviously this requires you manually moving them).
> 
> How did you approve changes? I am confused on how to do that

Go to files changed and it's under review changes.

**Comment by PullRequestMaster** [comment]
> > > As long as existing users aren't impacted (obviously this requires you manually moving them).
> > 
> > 
> > How did you approve changes? I am confused on how to do that
> 
> Go to files changed and it's under review changes.

Thanks :)

**Review by BukkitIsEnchanted — COMMENTED** [review]
This looks good to me.

**Comment by RhinosF1** [comment]
@PullRequestMaster if you want some help please do pop onto IRC. See https://meta.miraheze.org/wiki/IRC

**Pull request merged**
