### PR TITLE
NDKilla said this was already defined...

### PR DESCRIPTION
**Pull request by DeltaQuad-DQ**
...but it seems it is not

### CODE REVIEW

**Comment by JohnFLewis** [comment]
This is enabled on every wiki by default already.

**Comment by DeltaQuad-DQ** [comment]
@JohnFLewis then why is this not working? https://elements.miraheze.org/wiki/Template:Infobox_element

**Comment by DeltaQuad-DQ** [comment]
@JohnFLewis how do I fix said error?

**Comment by JohnFLewis** [comment]
Making an edit to the page will likely fix it

**Comment by DeltaQuad-DQ** [comment]
@JohnFLewis that completely broke it! Look what happened to the page

**Comment by DeltaQuad-DQ** [comment]
@JohnFLewis What has happened to the template? It's completely broken.

**Pull request closed without merging**
