### PR TITLE
Enable Flow on Elements wiki for T1207

### PR DESCRIPTION
**Pull request by DeltaQuad-DQ**
I believe that there is more to do than this, but this is all I know how to do

### CODE REVIEW

**Comment by DeltaQuad-DQ** [comment]
Hello? Is this being ignored? @Reception123 @JohnFLewis

**Comment by JohnFLewis** [comment]
It's not.

Needs [parsoid](https://github.com/miraheze/puppet/blob/master/modules/parsoid/manifests/init.pp) config however to work.

**Comment by DeltaQuad-DQ** [comment]
@JohnFLewis I don't know how to do that. As noted above, this request contains the settings that I know how to configure. Someone else will need to take care of the rest.

**Comment by JohnFLewis** [comment]
Okay, I've done it at miraheze/puppet@3433bead595ba9f5fbe68d19d428bdb58144df07.

**Pull request merged**
