### PR TITLE
DynamicPageList edit for my wiki

### PR DESCRIPTION
**Pull request by Njsmooth**
Hope I formatted it right this time

### CODE REVIEW

**Comment by Universal-Omega** [comment]
This is available in Special:ManageWiki/settings.

**Comment by Njsmooth** [comment]
> This is available in Special:ManageWiki/settings.

I apologize in advance, but I can't find it. Which tab should I look in?

**Comment by Universal-Omega** [comment]
parserfunctions

**Comment by Njsmooth** [comment]
Sorry again, but I don't see anything there for Dynamic Page Lists

**Comment by Universal-Omega** [comment]
> Sorry again, but I don't see anything there for Dynamic Page Lists

Are you using DynamicPageList or DynamicPageList3? This config is for DPL (Wikimedia) not DPL3

**Comment by Njsmooth** [comment]
DPL3

**Comment by Universal-Omega** [comment]
> DPL3

Yeah then you won't see them, these configs would not effect DPL3 anyways, on the Wikimedia one.

**Comment by Njsmooth** [comment]
Huh, I thought they shared configs, hence the conflicts. Would there be a config that does the same thing I'm trying to do for DPL3?

**Comment by Njsmooth** [comment]
@Universal-Omega Ok, I figured out DPL3's actual config names, could I reopen this and add the DPL3 configs?

**Comment by Universal-Omega** [comment]
> @Universal-Omega Ok, I figured out DPL3's actual config names, could I reopen this and add the DPL3 configs?

Sure, but DPL3 configs should be done in LocalWiki.php instead, so another PR would probably be easier.

**Comment by Njsmooth** [comment]
Ah, ok, thanks!

**Comment by Universal-Omega** [comment]
No problem.

**Pull request closed without merging**
