### PR TITLE
missing-wiki: add archive.org link

### PR DESCRIPTION
**Pull request by RhinosF1**
per discord suggestion

### CODE REVIEW

**Comment by dmehus** [comment]
LGTM. My _only_ small suggestion might be to add a `,<br /> ` immediately preceding the `or` addition, for smaller monitors and screens. Aesthetically, it may look a little unbalanced otherwise with this one long line of text relative to really short lines of text elsewhere on the page?

**Comment by dmehus** [comment]
This still hasn't been merged?

**Comment by RhinosF1** [comment]
I was hoping for some feedback

**Comment by dmehus** [comment]
@RhinosF1 It'd be nice to have some more comments...I would still add that one `<br />`, but otherwise, if no feedback, I'd take that to mean there's no opposition to it / no one really minds either way. Ah, I see you've requested a review from @paladox and @JohnFLewis, that's probably a good idea! :)

**Pull request merged**
