### PR TITLE
Sitenotice: add notice about ES

### PR DESCRIPTION
**Pull request by RhinosF1**

### CODE REVIEW

**Comment by Universal-Omega** [comment]
I don't think that this is necessary and if it is, and this is kept permanently (during ES migrations) then it should be done differently, rather than sitenotice.php in my opinion.

**Comment by RhinosF1** [comment]
> I don't think that this is necessary and if it is, and this is kept permanently (during ES migrations) then it should be done differently, rather than sitenotice.php in my opinion.

This is only set to show up while search is disabled. My plan is to do it in batches so it's not going to be on every wiki at every point.

**Comment by Universal-Omega** [comment]
> > I don't think that this is necessary and if it is, and this is kept permanently (during ES migrations) then it should be done differently, rather than sitenotice.php in my opinion.
> 
> This is only set to show up while search is disabled. My plan is to do it in batches so it's not going to be on every wiki at every point.

I know, but I don't like making this a permanent change, or even a few months. Search being disabled during the enabling of CS is always going to be necessary I believe.

**Comment by RhinosF1** [comment]
Where's a few months coming from?

**Comment by Universal-Omega** [comment]
Since this can't be done right now, closing.

**Pull request closed without merging**
