### PR TITLE
Enable StopForumSpam globally

### PR DESCRIPTION
**Pull request by AgentIsai**
- [ ] Enable in Global settings
- [ ] Grant right to `user` by default?

### CODE REVIEW

**Comment by Naleksuh** [comment]
Can users opt out of enabling this?

**Comment by AgentIsai** [comment]
I thought about making it a default extension but it wouldn't make sense with TorBlock also being global and not default.

**Comment by Naleksuh** [comment]
It is different because whether or not an IP is a Tor exit node is an objective fact, this extension is just blocking edits based on a specific abuse report by a third party. It's not the responsibility of a wiki host to prevent people from editing even if the wiki might want them to

**Comment by Reception123** [comment]
Couldn't the wiki manually unblock the IPs though? Or am I misunderstanding?

**Comment by Naleksuh** [comment]
@Reception123 My understanding is that this extension doesn't use Special:Block and just prevents them from doing things, sort of like TorBlock

**Comment by Reception123** [comment]
We will be adding sfsblock-bypass (similar to torunblocked) and therefore allowing users to opt out from it.

**Pull request merged**
