### PR TITLE
Localize extensions that are not absolutely required (redo)

### PR DESCRIPTION
**Pull request by Amanda-Catherine**
To-do list:

- [x] Remove extensions from GlobalExtensions.php
- [x] Add extensions to LocalExtensions.php and LocalSettings.php
- [x] Enable ManageWikiExtensions for localized extensions
- [x] Travis CI Check passes after all commits have been added
- [x] Manual syntax/code review by Amanda
- [x] Approval from sysadmins/stewards from a non-technical perspective
- [x] Manual syntax/code review by one or more sysadmins
- [ ] Merge PR

### CODE REVIEW

**Comment by Amanda-Catherine** [comment]
This is a redo of #2469 which ran into conflicts while trying to add commits. Please see the previous pull request for discussion and comments.

**Comment by Amanda-Catherine** [comment]
Syntax/code looks fine to me. Sysadmin review is now needed @JohnFLewis @MacFan4000 @paladox

**Comment by JohnFLewis** [comment]
Stewards don’t really have a say this is technical.

**Comment by JohnFLewis** [comment]
Change looks fine, just needs proper deployment

**Comment by Amanda-Catherine** [comment]
I thought that a steward should comment in a non-technical capacity since this does have some small social/community aspects.

**Pull request merged**
