### PR TITLE
Add extension MediaWikiChat to ManageWiki

### PR DESCRIPTION
**Pull request by bonnedav**

### CODE REVIEW

**Comment by MacFan4000** [comment]
This doesnt need to be in ManageWiki, the permissions won’t show up unless the extension is enabled on the given wiki.

**Comment by MacFan4000** [comment]
See https://github.com/miraheze/mw-config/blob/master/LocalSettings.php#L1044

**Comment by JohnFLewis** [comment]
"This doesnt need to be in ManageWiki" why?

**Comment by MacFan4000** [comment]
The reason is whatever the reason was that you didn’t add it @JohnFLewis

**Comment by JohnFLewis** [comment]
The reason is I didn't.

**Comment by bonnedav** [comment]
Why not just add it?

**Comment by JohnFLewis** [comment]
It should be.

**Pull request merged**
