### PR TITLE
Fix confirmed group globally/by default

### PR DESCRIPTION
**Pull request by sau226**
Autoconfirmed users never had the patrol right. This grants confirmed users the autoconfirmed users' IP based rate limit bypass and removes the confirmed users' right to patrol edits.

### CODE REVIEW

**Comment by sau226** [comment]
Err why exactly do confirmed users need the patrol right?

**Comment by JohnFLewis** [comment]
@reception123 easy merge here that’s been waiting a while.

**Comment by Reception123** [comment]
@JohnFLewis I never merged this because I wasn't sure, was this done intentionally at the beginning? Or was it a mistake?

**Comment by Southparkfan** [comment]
Makes sense.

**Pull request merged**
