### PR TITLE
Testing 4 new extensions

### PR DESCRIPTION
**Pull request by DeltaQuad-DQ**

### CODE REVIEW

**Comment by DeltaQuad-DQ** [comment]
@Reception123 @JohnFLewis Several issues have occurred since the merging of this pull request.

* The confirmed, autopatrolled, and rollbacker groups have mysteriously disappeared, along with the sysop right to add/remove them.

* Bureaucrats can access Special:RenameUser

* The "comment administrator" user group is not assignable by anyone

* The appropriate interfaces for the comments extension and the TorBlock extension both do not seem to exist.

**Comment by Reception123** [comment]
@DeltaQuad-DQ Could you please assign bureaucrat to me on your wiki so I can confirm the RenameUsers

**Comment by DeltaQuad-DQ** [comment]
@Reception123 you currently do not have an account on the wiki. Note that this is not Elements - this is deltaquadtest.miraheze.org

**Comment by Reception123** [comment]
@DeltaQuad-DQ All the permission related issues were caused by you missing a + in front of the DB name, which overrides the "default" permissions.

**Comment by DeltaQuad-DQ** [comment]
@Reception123 OK - the permission issues are fixed, and the missing user groups are back. However, the "comment administrator" user group is still unassignable, and the interfaces for the comments and TorBlock extensions are still missing.

**Comment by Reception123** [comment]
@DeltaQuad-DQ Comment admin needs to be assinged in $wgAddGroups I believe.. Per https://deltaquadtest.miraheze.org/wiki/Special:Version, TorBlock is enabled. It doesn't have a special page, all it does is block connections from Tor

**Comment by DeltaQuad-DQ** [comment]
@Reception123 OK, but bureaucrats also have commentadmin rights without the additional user group, and there is no option to add comments on the wiki page.

**Comment by DeltaQuad-DQ** [comment]
@Reception123 the '*' group is supposed to have the right to submit comments.

**Comment by DeltaQuad-DQ** [comment]
@Reception123 also the contact extension isn't working either - it says that I don't have a valid email address set even though I do

**Comment by JohnFLewis** [comment]
I can't see any comment pages on the wiki.

And there is no use by the name "DeltaQuad Test Wiki" therefore there isn't a valid email address set.

**Comment by DeltaQuad-DQ** [comment]
@JohnFLewis I fixed the contact error in #1185 

What do you mean by "no comment pages"? Shouldn't you be able to add comments to any page on the wiki?

**Comment by JohnFLewis** [comment]
No, you need to add a comment section by adding "<comments/>" to the page

**Comment by JohnFLewis** [comment]
It uses the information of the user.

**Comment by DeltaQuad-DQ** [comment]
@JohnFLewis thanks. However, I was just very dumb and locked myself out of the wiki by removing my sysop flag - can you please restore it?

**Comment by JohnFLewis** [comment]
Re-added

**Pull request merged**
