### PR TITLE
GlobalUserPage + GlobalPreferences per T1681

### PR DESCRIPTION
**Pull request by MacFan4000**

### CODE REVIEW

**Comment by Reception123** [comment]
Blocked by T1681

**Comment by sau226** [comment]
Now we just need an RfC to render a yes or no answer

**Comment by MacFan4000** [comment]
I think its a yes, as there are currently more support votes (3:6).

**Comment by Reception123** [comment]
@MacFan4000 Yikes, this commit has so many new changes and conflicts.

You should either open a new PR, or if you prefer I can directly commit it when I install.

**Pull request closed without merging**
