### PR TITLE
Add FameData and WikiData to import

### PR DESCRIPTION
**Pull request by CloakSelf**
Add FameData and wikidata to import options for memedata

### CODE REVIEW

**Review by Universal-Omega — CHANGES_REQUESTED** [review]
Formatting; syntax

**Comment by CloakSelf** [comment]
> Formatting; syntax

I can't see it???

**Comment by Universal-Omega** [comment]
> > Formatting; syntax
> 
> I can't see it???

indentation

**Comment by Universal-Omega** [comment]
* Superceded by #4206

**Comment by CloakSelf** [comment]
@Universal-Omega tysm, could not figure out what went wrong.

**Pull request closed without merging**
