### PR TITLE
Userrights for wikiyangtzewiki (revocations)

### PR DESCRIPTION
**Pull request by MWIA**

### CODE REVIEW

**Comment by MWIA** [comment]
Well, can someone at least acknowledge this request? I need to know that it is being addressed.

**Comment by Reception123** [comment]
Sock of LP

**Comment by MWIA** [comment]
@Reception123 please re-open this. I have no reason to be locked globally as I have not broken any Miraheze rules by this GitHub behavior.

See also the email sent to staff@miraheze.org earlier today.

**Comment by MWIA** [comment]
@Reception123 @NDKilla Hello? I would appreciate it if you carried out my request, or at the very least, responded to my staff@miraheze.org email.

I don't appreciate being told that my behavior was against policy when to the best of my knowledge it was not.

**Pull request closed without merging**
