### PR TITLE
make none of the above first createwiki purpose

### PR DESCRIPTION
**Pull request by Reception123**
I think it makes more sense to have it default to none of the above instead. And yes, I do realise then it should probably be called "None of the options below" rather than above

### CODE REVIEW

**Comment by Universal-Omega** [comment]
It's not none of the above if it's the top one.

**Comment by Reception123** [comment]
> It's not none of the above if it's the top one.

Heh we conflicted, I just edited my initial comment to say that

**Comment by Universal-Omega** [comment]
Maybe we should make the key be '' and default it to that in CW itself?

**Comment by RhinosF1** [comment]
> Maybe we should make the key be '' and default it to that in CW itself, then keep the none of the above options at the bottom but still default to it?

That makes more sense

**Comment by dmehus** [comment]
@Reception123 I disagree. The idea was _not_ to have a "none of the above" purpose. I believe it should be removed, and additional purposes should be added. The initial list was a temporary, non-exhaustive list, and @Universal-Omega promised me we'd add additional purposes as required. Otherwise, we defeat the whole purpose behind CreateWiki learning from the predefined purpose field.

**Comment by dmehus** [comment]
I originally wanted this to be a **mandatory field** users _had_ to select, so I'd rather prefer the top option to be an unselectable _blank_ option

**Comment by Reception123** [comment]
> I originally wanted this to be a **mandatory field** users _had_ to select, so I'd rather prefer the top option to be an unselectable _blank_ option

But what if none of the purposes match?

**Comment by Reception123** [comment]
> > I originally wanted this to be a **mandatory field** users _had_ to select, so I'd rather prefer the top option to be an unselectable _blank_ option
> 
> But what if none of the purposes match?

@dmehus you never answered

**Pull request closed without merging**
