### PR TITLE
Update pculsdwiki logo

### PR DESCRIPTION
**Pull request by sensodalin**

### CODE REVIEW

**Comment by Pix1234** [comment]
Looks good sadly i cant merge.

**Comment by sensodalin** [comment]
Why you can not merge it?

**Comment by Pix1234** [comment]
Im not able to due to the repo permissions. It will get merged hopefully by someone else at some point hopefully.

**Comment by sensodalin** [comment]
So, How can I update my logo then?

**Comment by Reception123** [comment]
@sensodalin I will merge but I would ask you to please stop creating so many PRs. They are confusing, as we do not know which one to merge, and PRs can be EDITED. I will be closing all the others.

**Comment by sensodalin** [comment]
Okay I see, thanks for your working hard!

**Pull request merged**
