### PR TITLE
Revert "Revert "add gratisdata.miraheze.org as wgCrossSiteAJAXdomains on gratispaideiawiki""

### PR DESCRIPTION
**Pull request by ugochimobi**
I'd need this, still

### CODE REVIEW

**Comment by Universal-Omega** [comment]
You told me it didn't work.

**Comment by ugochimobi** [comment]
> You told me it didn't work.

Yeah, it didn't work for the authority control stuff, but worked for some other things.
You told me you'd look into it for me :)

**Comment by Universal-Omega** [comment]
> > You told me it didn't work.
> 
> Yeah, it didn't work for the authority control stuff, but worked for some other things. You told me you'd look into it for me :)

I haven't yet looked into that but reverted this thinking it hadn't worked at all.

**Comment by ugochimobi** [comment]
Oh, sorry about that, it did.

**Comment by Universal-Omega** [comment]
I still have some concerns with doing this anyway. It allows cross-wiki authentication, which is the reason we only allow metawiki and loginwiki at the moment. So I don't know if we really do want to allow this.

**Review by Universal-Omega — CHANGES_REQUESTED** [review]
This shouldn't be merged unless we are sure we can really do this, without having issues.

**Pull request closed without merging**
