### PR TITLE
Allow CVT to add/remove bot flag to/from themselves on metawiki

### PR DESCRIPTION
**Pull request by MacFan4000**
This allows them to prevent themselves from spamming RecentChanges when doing lots of Locks/Blocks etc. NOTE: This does not allow them to add anyone to the group, just themselves.

### CODE REVIEW

**Comment by JohnFLewis** [comment]
Why not in LS?

**Comment by MacFan4000** [comment]
@JohnFLewis Where would it be done in LS?

**Comment by JohnFLewis** [comment]
Under group permissions sections with all the other group permission settings.

**Comment by MacFan4000** [comment]
Those variables arn’t even in the file right now afaik, since they havn’t really been used on any wikis.

**Comment by The-Voidwalker** [comment]
https://github.com/miraheze/mw-config/blob/master/LocalSettings.php#L5784 for remove from self
add to self needs to be added somewhere around https://github.com/miraheze/mw-config/blob/master/LocalSettings.php#L4643

**Comment by MacFan4000** [comment]
Done

**Comment by Reception123** [comment]
Approved by @The-Voidwalker as a steward, therefore good to go.

**Pull request merged**
