### PR TITLE
Adding VE, logo and favicon for allbanks2wiki

### PR DESCRIPTION
**Pull request by Wirlie**
Request: https://meta.miraheze.org/wiki/Request_features#AllBanks2_.28Status:_Open.29

### CODE REVIEW

**Comment by Wirlie** [comment]
I'm not sure if I edited the permissions correctly, any comment is welcome. Thank you.

**Comment by revi** [comment]
LGTM but blocked by miraheze/puppet#139 where I do not have permission to merge.

**Comment by Wirlie** [comment]
okay, then I'll wait until they review my PR.
Thanks.

**Comment by labster** [comment]
At some point we really need to come up with a configuration group for admin edit only wikis like this, because it's a common request.

Anyway, merged, thanks!

**Comment by Wirlie** [comment]
Thanks to you, again :)

**Pull request merged**
