### PR TITLE
Add SocialProfile and WikiForum to allthetropeswiki for T761

### PR DESCRIPTION
**Pull request by LegoFan4000**

### CODE REVIEW

**Comment by Reception123** [comment]
SocialProfile needs copying of directories, and since last time I didn't do it properly I am leaving this to someone else.

**Comment by LegoFan4000** [comment]
As I have said before there is no tab key in iOS

**Comment by NDKilla-public** [comment]
@LegoFan4000 Tabbing doesn't mean literally use the tab key, it means fix the indentation. In this case, if you compare the added lines to the rest of the lines, you actually have one to many space (on each line, before the first ' )

**Comment by NDKilla-public** [comment]
@LegoFan4000 also it's not as important since someone else will probably eventually fix it, but these should be alphebatized

**Pull request merged**
