### PR TITLE
Let otf files recognise application/vnd.ms-opentype mime type

### PR DESCRIPTION
**Pull request by Universal-Omega**
Per [T7506](https://phabricator.miraheze.org/T7506)

### CODE REVIEW

**Review by RhinosF1 — CHANGES_REQUESTED** [review]
Please just handle upstream. Patch is at https://gerrit.wikimedia.org/r/c/mediawiki/core/+/700632

**Comment by Universal-Omega** [comment]
> Please just handle upstream. Patch is at https://gerrit.wikimedia.org/r/c/mediawiki/core/+/700632

Yeah but then we have to wait until at least 1.36.1 before we can get it to work, I think.

**Comment by RhinosF1** [comment]
> > Please just handle upstream. Patch is at https://gerrit.wikimedia.org/r/c/mediawiki/core/+/700632
> 
> Yeah but then we have to wait until at least 1.36.1 before we can get it to work, I think.

Why can't we cherry pick?

**Comment by RhinosF1** [comment]
Picked from core directly

**Pull request closed without merging**
