### PR TITLE
disable anon edit on antiguabarbadoswiki

### PR DESCRIPTION
**Pull request by Reception123**
Per request

### CODE REVIEW

**Comment by JohnFLewis** [comment]
Variable does not exist.

**Comment by JohnFLewis** [comment]
Bad syntax, wrong location.

**Comment by Reception123** [comment]
What location should it be?

**Comment by JohnFLewis** [comment]
bottom of the file next private/closed variables?

**Comment by Reception123** [comment]
Okay. will do and will fix syntax #71 (i guess)

**Pull request closed without merging**
