### PR TITLE
why was darkmode a default extension?

### PR DESCRIPTION
**Pull request by Universal-Omega**

### CODE REVIEW

**Comment by Pix1234** [comment]
To make darkmode possible globally afaik

**Comment by Universal-Omega** [comment]
> To make darkmode possible globally afaik, PRs shouldnt be used to ask questions.

Fair point. It was more rhetorical. But why would it want to be made global? It doesn't even really work right.

**Comment by Pix1234** [comment]
I think it was by request. Regardless theres no harm leaving it way it is

**Comment by Universal-Omega** [comment]
> I think it was by request. Regardless theres no harm leaving it way it is

I suppose that's fair enough.

**Pull request closed without merging**
